### ISSUE TITLE
Pocketcasts not working

### ISSUE THREAD

**Issue by gausie** [berrberr/streamkeys#100]
The buttons... they do nothing!

**Comment by berrberr** [comment]
Are you sure? It works for me. URL I'm testing: https://play.pocketcasts.com/web#/podcasts/show/6dabeac0-0423-012e-f9a0-00163e1b201c

It's possible that Streamkeys was updated while the tab was in use (which requires a tab refresh to resync again :\)

**Comment by gausie** [comment]
You're quite right. Apologies and I'd close the ticket if I wasn't replying
via email!

**Comment by berrberr** [comment]
NP :+1:
