### ISSUE TITLE
Streamkeys hijacks iTunes control with media buttons

### ISSUE THREAD

**Issue by domharrington** [berrberr/streamkeys#103]
When I have chrome open with the streamkeys extension and no music sites open, the media control buttons no longer work to control the native iTunes app. Is this a known issue?

Chrome: Version 43.0.2357.81 (64-bit)
iTunes: Version 12.1.2.27
Streamkeys: Version 1.4.8

**Comment by berrberr** [comment]
Known issue, it's actually a problem with how Chrome handles global keys. Nothing we can do until that is fixed! See #80 for more info

**Comment by domharrington** [comment]
Thanks for the reply and link to existing issue. Will subscribe to that!
