### ISSUE TITLE
Popup should only show player controls for tabs with players.

### ISSUE THREAD

**Issue by nemchik** [berrberr/streamkeys#111]
If you go to the youtube home page there is no player, and many pages on youtube do not have players. The popup shows player controls for every open tab of any supported site, but it should only show the player controls if a tab is detected as having a player.

**Comment by Illyism** [comment]
Guess it would simply be a change to only enable it on urls starting with `watch`

**Comment by berrberr** [comment]
Yeah this is a good idea and something I have been meaning to add. The feature should only be needed for sites that are more than just a player (Amazon comes to mind as a big one).

The `Sitelist` already *sort of* does this by letting you set a subdomain (for example, we use `play.google` so the content script is not injected into every google page).

There is also an `alias` property on sites in `Sitelist` that lets you expand what the regex will match, so what we need is the inverse of that to filter out some matches. I will take a look.

**Comment by nemchik** [comment]
Just wanted to put an update here, I referenced this issue in a comment on https://github.com/berrberr/streamkeys/pull/119 which is now merged so maybe this would be a better place to continue the conversation since it's still open.

**Comment by berrberr** [comment]
Fixed in #119
