### ISSUE TITLE
Consider not showing media controls that are not available with certain controllers

### ISSUE THREAD

**Issue by nemchik** [berrberr/streamkeys#114]
For example some sites do not have options to like/dislike tracks, and some sites do not let you use the previous song function.

For the sake of keeping the interface tidy it might be a good idea to grey those icons out to make it visually obvious to the user that a function is not available, rather than completely removing buttons from the popup when a player lacks support for that function.

**Comment by berrberr** [comment]
Yeah, this has been on the todo list. It's a pretty simple addition too, add the features that the site supports in the call to `getPlayerState` and then add a `.disabled` class to the popup buttons for features that the site does not support.
