### ISSUE TITLE
Editing a text field breaks media key bindings

### ISSUE THREAD

**Issue by c24w** [berrberr/streamkeys#120]
Using Chrome Version 43.0.2357.125 (64-bit) with GNOME 3 on Arch Linux.

For example, the default _Media Play/Pause_ binding works great out-of-the-box; however, it breaks as soon as I start typing in a text field/area, with GNOME flashing up a :no_entry_sign: for a few seconds.  Binding _Toggle play/pause_ to something else (Ctrl+Shift+Space) doesn't suffer with this problem and works even as I'm typing this :)

**Comment by berrberr** [comment]
Sounds like a Chrome bug! Does the same behavior happen with other extensions? If so, make a ticket here: https://code.google.com/p/chromium/issues/list

**Comment by c24w** [comment]
You're right - it does happen with another similar extension.
