### ISSUE TITLE
Popup is empty when an Amazon shopping tab is open with no other players

### ISSUE THREAD

**Issue by nemchik** [berrberr/streamkeys#131]
As of 1.5.0 if I close all tabs and go to amazon.com for shopping and look at the popup it has the blue bars at the top and bottom, but no players are shown, and `.js-no-sites` is not shown either.

This was discussed briefly in https://github.com/berrberr/streamkeys/issues/111 and https://github.com/berrberr/streamkeys/pull/119 but not resolved.

**Comment by berrberr** [comment]
Fixed in 1.5.2.
