### ISSUE TITLE
Replay when pressing play (e.g. on YouTube)

### ISSUE THREAD

**Issue by aouaki** [berrberr/streamkeys#135]
When a YouTube video (not in a playlist) is finished, I think that pressing play should play it again. Maybe should this be only an option?

**Comment by berrberr** [comment]
Yeah I like this idea :+1: 

I'm doing work on the options page right now for the next release, & I'll add this option in there (defaulted to disabled)

Thanks for the suggestion :smile_cat:

**Comment by berrberr** [comment]
Added!
