### ISSUE TITLE
Make streamkeys button as pause/play button

### ISSUE THREAD

**Issue by Bomberlt** [berrberr/streamkeys#141]
I want to have streamkeys button in chrome extensions bar to act as a pause/play button. I mean that instead of opening menu with all opened streaming sites with buttons it could act as just pause/play button for last paused stream.

For example [SoundCloud Button](https://chrome.google.com/webstore/detail/soundcloud-button/gdkpgbhhfnpjiembbpifcpfalfnflmop?hl=en) behaves this way.

I know that stream keys should support many stuff at the same time so this could also maybe be an another extension.

If this enhancement seems to not align with your plans or you think that this is not worth to implement, maybe I can clone this project and try to make separate extension for this purpose? And maybe you can say if that would be hard or not for people not having a lot js experience?

**Comment by berrberr** [comment]
This is an interesting suggestion...haven't even thought of anything like this.

I think with the way that the extension is set up this does not make sense to add.

However, it is pretty easy to add if you are interested. Adding this line in `background.js` should do it (note: untested :))

```
chrome.browserAction.onClicked.addListener(function(tab) {
  sendAction("playPause");
});
```

Also note this will send the `playPause` action to ALL active tabs. Currently we don't keep track of the "last" paused item (although its on the roadmap...)

**Comment by Bomberlt** [comment]
Thanks for reply! Definitely gonna try this.

**Comment by Bomberlt** [comment]
If anyone is interested made the change - [Bomberlt/streamkeys/commit/1a50aa13977c7b6b17e16e77d0a2c0075e4d1d78](https://github.com/Bomberlt/streamkeys/commit/1a50aa13977c7b6b17e16e77d0a2c0075e4d1d78). Now it plays/pauses "most recent" tab. For now "most recent" is allways first active tab.

Thinking about adding this to Chrome Web Store..
