### ISSUE TITLE
Add Plex without myPlex

### ISSUE THREAD

**Issue by Eun** [berrberr/streamkeys#153]
If you use Plex without myPlex the extention won't work (bc you are checking only the url for `plex.tv`).

The easy way would be to allow a customization of the url in `Sitelist.js`, or maybe use an array that is customizeable?

**Comment by berrberr** [comment]
Yeah, I think a cool thing to add for the future would be a custom URL mapping section to the options page.

For short term you can use this method described here: #41

**Comment by dhulihan** [comment]
+1
