### ISSUE TITLE
Youtube new transparent controls breaks the functionality

### ISSUE THREAD

**Issue by mmorelo** [berrberr/streamkeys#154]
Since August, YT new transparent player controls breaks the YoutubeController.js functionality. 

I was also wondering why the JS code do not access the YT api for player.getplayerstate(). It might work, right?

**Comment by berrberr** [comment]
Hey, can you give me some more info? Youtube is working properly for me. Where can I see this transparent player? I did some quick googling and didn't find much.

**Comment by mmorelo** [comment]
Hey Alex,

The issue is that the function to recognise that the video is playing does
not work actually. You can also see that when you click the play on the
streamkeys, in some other websites the player switched to pause and
viceversa. In youtube, it sticks to play icon always, although it might be
playing already.

Best regards,
Francisco
