### ISSUE TITLE
Support for UpNext Player?

### ISSUE THREAD

**Issue by orschiro** [berrberr/streamkeys#163]
Dear all, 

Would it be possible for this great extension to support the Chrome Extension [UpNext Player](https://chrome.google.com/webstore/detail/upnext-music-player/dgkfcdlmdppfhbfmooinbcejdaplobpk)?

Thankfully,

Robert

**Comment by berrberr** [comment]
Theres no great way to do this, sorry.

**Comment by orschiro** [comment]
Dear @berrberr,

Nevertheless I appreciate your response.

Thanks!

~ Robert
