### ISSUE TITLE
Last update (15/12/04) break with Spotify which is now recognized as "Player.fm".

### ISSUE THREAD

**Issue by ginolon** [berrberr/streamkeys#166]
Last update (15/12/04) break with Spotify which is now recognized as "Player.fm" and all controls are disabled.

**Comment by berrberr** [comment]
Thanks for the report. What URL are you using for spotify? It seems to work for me with https://play.spotify.com/browse

**Comment by ginolon** [comment]
Yeah, the problem is this! My spotify redirect me on player.spotify.com. Before this update everything worked.

**Comment by berrberr** [comment]
Ah, OK it's a bug then :). I'll fix and release a fix soon

**Comment by berrberr** [comment]
Thanks again for the report! It should be fixed in v1.5.4 which I just pushed to Chrome store.
