### ISSUE TITLE
Google Play Music Not Detected

### ISSUE THREAD

**Issue by lukad03** [berrberr/streamkeys#169]
Latest updates breaks Google Play Music for me. When clicking the StreamKeys button with a Google Play Music tab open, it says 'No music sites open.'. Google Play Music is selected in my options and the extension is enabled.

Chrome: Version 47.0.2526.73 (64-bit)
Streamkeys 1.5.4

**Comment by berrberr** [comment]
Thanks for the report. Google Play music is working for me on 1.5.4.

Some questions:

What is the URL of your google play tab?
Does Streamkeys work for other sites?
Have you tried reinstalling the extension?
Can you open up developer tools on the google music tab (with Streamkeys installed) and see if there are any relevant console messages (will start with `STREAMKEYS-INFO` or `STREAMKEYS-ERROR`)

**Comment by lukad03** [comment]
Found the issue - I had selected Google Play in the 'Enabled Sites' options and thought that meant it was enabled. However it's the opposite. Perhaps this is a UI improvement that could be handled - i.e. instead of darkening disabled sites, lower the opacity on the element to better indicate that they aren't enabled.

Thanks!

**Comment by berrberr** [comment]
Glad you fixed it! Yeah, I agree that the options page is confusing right now. I am going to be doing a UI refresh soon which will add explicit enabled/disabled button to the options page and make the popup look nicer. You are not the first one to have this problem, so it is an issue :)
