### ISSUE TITLE
Youtube Up Next Feature

### ISSUE THREAD

**Issue by hdavidzhu** [berrberr/streamkeys#170]
Would it possible to map the next song button to Youtube's Autoplay suggestion? Similar to Pandora, I would like to skip to the next song sometimes.

![screenshot from 2015-12-14 00 15 27](https://cloud.githubusercontent.com/assets/3756871/11773441/f7cec674-a1f7-11e5-974d-a2399b499527.png)

**Comment by berrberr** [comment]
Good idea, I'll look to add it in next release.

**Comment by leocaseiro** [comment]
I think this is working already. I pressed (next) and it changed.
