### ISSUE TITLE
click on streamkeys icon to toggle the capturing of next/prev keys from the system

### ISSUE THREAD

**Issue by sktguha** [berrberr/streamkeys#171]
It would be great to have a feature to click on the extension's icon to disable the capturing of the keys. Sometimes my native player (as windows media player ) is running and I need to control it but streamkeys doesn't allow me to. I can file a PR if you show me the relevant files

Also I suggest to add this github repo's address on the chrome extension page. I looked earlier there for streamkeyes github repo but found it only later on the website

**Comment by berrberr** [comment]
Hey,

I would love to add something like this, but to the best of my knowledge it's not currently possible! Streamkeys uses the Chrome commands API (https://developer.chrome.com/extensions/commands) with the global flag set to true to capture hotkeys. As you can see from the docs, the things that you can do with the API is quite limited.

Adding the ability to pause hotkey capturing would be awesome and make Streamkeys so much better, but Chrome doesn't let us do it. My best suggestion (and what I do) is to just bind your hotkeys to something other than media keys so they don't conflict with the other players.

**Comment by sktguha** [comment]
Ah I see. Thanks for replying. In that case is it possbile to capture only when chrome is in focus ?

**Comment by berrberr** [comment]
Yes, go to `chrome://extensions`, click "keyboard shortcuts" and change the Streamkeys hotkeys from "Global" to "In Chrome"

**Comment by sktguha** [comment]
ah great. Thanks. maybe you can also add this in your extension's readme :). A lot of users have mentioned about this issue. Also it would be good to add this repo's address there :). l
