### ISSUE TITLE
Not working in chrome nor chromium in Ubuntu 15.10

### ISSUE THREAD

**Issue by idurandiaz** [berrberr/streamkeys#172]
Even tough when youtube is open the icon detects the website and shows the media controls, still my media keys of my keyboard won't work. I know the media keys work as they do in a similar add-on in firefox. I use your extension in Mac in the same machine with same keyboard and it works perfectly.

**Comment by idurandiaz** [comment]
Found the solution. I had to unbind the media keys from Ubuntu's sound and media keyboard shortcuts. Now it is working fine.

**Comment by berrberr** [comment]
Cool, thanks for reporting info.
