### ISSUE TITLE
Add support for Coursera.org

### ISSUE THREAD

**Issue by idurandiaz** [berrberr/streamkeys#173]
Could you add support for coursera.org? I use it all the time, even tried to add it myself following your "Adding Sites" instructions but didn't succeed.

**Comment by berrberr** [comment]
I'll look to add it to next version.

**Comment by idurandiaz** [comment]
That would be great. Looking forward to it! 

There are two more websites that are similar to Coursera and it would be even greater if you add support to them as well: edx.org and treehouse.com.

Thanks!
