### ISSUE TITLE
Fix support for TheSixtyOne.com

### ISSUE THREAD

**Issue by KsaRedFx** [berrberr/streamkeys#178]
Buttons in the drop down UI are unresponsive, and hitting physical media keys on my keyboard also cause no response for this site alone.

Other sites such as YouTube and Pandora work fine.

**Comment by KsaRedFx** [comment]
![image](https://cloud.githubusercontent.com/assets/1790490/12573728/7293b4c0-c3ca-11e5-8d6d-00f59ef11a9e.png)

**Comment by berrberr** [comment]
Thanks for the report, looks like they changed their site. Will fix for next release.
