### ISSUE TITLE
Coursera.org

### ISSUE THREAD

**Issue by idurandiaz** [berrberr/streamkeys#182]
Thanks for adding coursera.org to v1.5.5, however it is not working for me, youtube and everything else works fine, but not coursera. Is it supposed to be working already in v1.5.5? I have tried it in both Mac and Linux (ubuntu) without luck.

**Comment by berrberr** [comment]
Thanks for the report. Can you provide me with an example URL that doesn't work for you? It seems to be working for me, but there might be other players I am not aware of (not very familiar with the site).

**Comment by idurandiaz** [comment]
Sure, here there are two of them:

- https://www.coursera.org/learn/galois/lecture/1Enrk/introduction-to-galois-theory
- https://www.coursera.org/learn/algorithmic-toolbox/lecture/EagcP/welcome

You are right, they seem to to use two different players at least. The above links have their new course format for which your extension doesn't work, however for old format courses, your extension DOES work, such as this one: https://class.coursera.org/algo-004/lecture (I hadn't noticed that before).

Thanks in advance for all your efforts!

**Comment by berrberr** [comment]
Thanks for the links, there do seem to be multiple players. I'll look into it adding support for those in next update.

**Comment by idurandiaz** [comment]
That would be great. Thanks!
