### ISSUE TITLE
On/Off switch in dialog

### ISSUE THREAD

**Issue by petrleocompel** [berrberr/streamkeys#183]
It would be great to have an switch in dialog 
![1](https://cloud.githubusercontent.com/assets/9423543/13487467/7efca20e-e11a-11e5-8da4-31e3370f2267.png)

Because if I want to use media keys on iTunes or other players I have to deactivate whole extension.

**Comment by petrleocompel** [comment]
Maybe keyboard shortcut would be also useful.

**Comment by berrberr** [comment]
Would love to add this (and it's been suggested before :wink:), however current Chrome extension APIs make this impossible. There is no way to enable/disable an extension capturing hotkeys from the extension itsself. This can only be done via a user manually disabling an extension (or changing/removing hotkeys).

What I have been recommending (and doing myself) to people who use the media keys elsewhere is to bind Streamkeys hotkeys to some other keys (eg. currently for me play/pause is cmd+shift+2)
