### ISSUE TITLE
group enabled sites vs disabled sites

### ISSUE THREAD

**Issue by klaernie** [berrberr/streamkeys#192]
It would be nice if all enabled sites would be shown on top of the options page, and all disabled below them.

Right now I noticed that want to set the priorities for my usual sites, so I disabled all of the unused ones, but the enabled ones are still all over the place.

**Comment by berrberr** [comment]
I like it. What do you think would be better: push all the disabled sites to the end of the list, or create two separate enabled/disabled sections?
