### ISSUE TITLE
priorities vs last-used

### ISSUE THREAD

**Issue by klaernie** [berrberr/streamkeys#193]
As far as I can tell streamkeys knows about which app is playing and as such which app was playing last when all are paused.

Would it be possible to replace the static priorities by a last-used method? So if I intend to start playing via the hotkey it should figure out which player/instance was running last and resume it, if it's still alive, or if it vanished (tab closed etc) resume with the next-older version? 

Maybe this is one way to solve #133 and should also build infrastructure for #58

**Comment by MHendricks** [comment]
I constantly have 3-6 youtube tabs open. Most of them are various playlists I want to continue watching at some point in the future. Every time I use the plugin at least 2 or 3 tabs start playing at once(which ever tabs have been loaded when I switch between them). I have to manually disable each of the players in streamkeys. 

Last used would be very useful. For movie players it almost could just work for the currently active tab. Perhaps this could be a per-site option.
