### ISSUE TITLE
Album title/art

### ISSUE THREAD

**Issue by bsinky** [berrberr/streamkeys#195]
Wondering why BaseController.selectors contains an album property which many child controllers specify (at least several that I've looked at), yet the album title isn't displayed in popup.html or used in popup.js.

Also, I think it'd be neat to have the ability to display album art, even if its a small thumbnail size, if an opened player provides it.  Thoughts?

I'd be interested in submitting a pull request for one/both features if it's within the scope of Streamkeys goals.  I've been playing both in a fork.

**Comment by berrberr** [comment]
Yeah, those selectors don't do anything (yet) :). It is something that I think people would like added, myself included. I guess the two big things required from this feature are:

1. It has to look good in the popup
2. It has to be performant

Also have to think about how site's that don't have album art will look in popup (especially open simultaneously with sites that _do_). I guess mostly just a bunch of styling questions to answer. Submit a PR when you're happy with it and we can go through it 👍
