### ISSUE TITLE
Google Play Music Always Disabled

### ISSUE THREAD

**Issue by AROAH1337** [berrberr/streamkeys#202]
Google Play Music will only show up under "Show Disabled Sites." Other sites work as expected, and the controls for GPM work, when clicked, but the ability to use hotkeys is disabled.

**Comment by dtoumey** [comment]
Yeah, I can confirm this issue, too!

**Comment by berrberr** [comment]
I can't reproduce this. Does it still happen?

I use GPM (literally) everyday and no issues for me :)

**Comment by AROAH1337** [comment]
Yep, still happens.

![image](https://cloud.githubusercontent.com/assets/7283348/16547366/c610674a-4130-11e6-8238-62a5d1e78496.png)

**Comment by AROAH1337** [comment]
Interesting thing I just found. It shows up as expected while the page is loading, but once it's loaded, it's disabled.

![2016-07-03_15-18-11](https://cloud.githubusercontent.com/assets/7283348/16547386/56ac3658-4131-11e6-9cf9-79af5d1f0cf5.gif)

**Comment by berrberr** [comment]
@AROAH1337 my guess is that you have GPM disabled in the Streamkeys settings page. If GPM is enabled, it should look something like this:

<img width="951" alt="screen shot 2016-08-07 at 12 56 09 pm" src="https://cloud.githubusercontent.com/assets/861000/17463850/737a0da4-5c9e-11e6-8a21-87747d48c0ad.png">

**Comment by AROAH1337** [comment]
That was the first thing I checked, unfortunately. I even tried adding the GPM URL as an alias, but no luck.

![image](https://cloud.githubusercontent.com/assets/7283348/17464345/c8a87ea2-5ca1-11e6-85ff-99a29e7702df.png)

**Comment by berrberr** [comment]
The red background means it's disabled. Click the "enable" button to enable it. Grey background means enabled.

**Comment by AROAH1337** [comment]
I'm just gonna... close this...

**Comment by berrberr** [comment]
I'm guessing that fixed it? :P

TBH, the options page design is much more confusing than I thought it would be. Multiple people are running into issues with it :\. I'm going to try to redesign some stuff to make it more clear when I get some time.
