### ISSUE TITLE
play/pause does not work with emby

### ISSUE THREAD

**Issue by svennp** [berrberr/streamkeys#205]
pause button does not work with emby.
i am able to start music with play button, but music will not pause.
skip track and previous tracks works great.
i have spesified the alias and i am connected to my own server.

**Comment by smalik0** [comment]
I am also experiencing this issue. Everything else works perfectly, but pausing something does not.

**Comment by spreadsheetaddict** [comment]
Issue appears to still be present as of 2018-01-29

**Comment by phoenix83** [comment]
This is still an problem. Maybe this issue was closed for being stale, but the problem remains.
