### ISSUE TITLE
Youtube Subscriptionpage priority

### ISSUE THREAD

**Issue by gforke97** [berrberr/streamkeys#207]
If i have the Soundcloud and the Youtube subscription page open (youtube.com/feed/subscriptions) and have set the priority of Youtube to 2 then it wont take the shortcuts on Soundcloud which is a big problem since i have the subscription page open all the time and would still like to be able to set the priority of the videos higher than soundcloud and be still able to use soundcloud when theres no video being played.

**Comment by berrberr** [comment]
Thanks! This is an edge case I totally overlooked :D

I'll add something for next release.
