### ISSUE TITLE
Media buttons on ubuntu

### ISSUE THREAD

**Issue by night5talker** [berrberr/streamkeys#214]
Hi

Im using ubuntu 16.04 and Im unable to use my media buttons, they work in windows, and on VLC (in linux)

can you investigate it

**Comment by berrberr** [comment]
Unfortunately nothing an extension can do here. This is a lower level issue/bug for the actual Chrome browser. 

Search or post it here: https://bugs.chromium.org/p/chromium/issues/list

Sorry!
