### ISSUE TITLE
Youtube `Skip Ad` shortcut

### ISSUE THREAD

**Issue by leocaseiro** [berrberr/streamkeys#216]
Hi, thanks for this awesome extension.

I was wondering if we could add some more shortcuts, for example to skip ad on youtube...

I'm happy to send a PR if you are interested in this feature, Perhaps the key 'S' or maybe Control + Next or Command + next.

Let me know your thoughts.

**Comment by berrberr** [comment]
Yeah this would be cool. It will have to be a user-defined thing (it would be a new `chrome.command`, and max default command hotkeys is 4).

If this functionality is added it would be super easy to take it one step further and auto click the skip add button when it pops up ... might go against youtube TOS though so IDK.

**Comment by filhit** [comment]
Ad skipping is already implemented in ad-blocker extensions. I think this extension should be focused on keys only.

**Comment by leocaseiro** [comment]
@filhit, I'm sorry, I think it's not clear. The idea is shortcut the button "skip the add".  I'm against adblocker because I monetize youtube videos myself.

**Comment by AddaxSoft** [comment]
I think this is out of the extension scope - you don't want to use ads blocker, then maybe you should consider a YouTube ads free red subscription?

**Comment by nemchik** [comment]
I agree this is king of out of scope, but it was pretty easy to do.

```
  BaseController.playNext = function() {
    if ($(".videoAdUiSkipButton") !== null) {
      $(".videoAdUiSkipButton").click();
    } else {
      this.click({action: "playNext", selectorButton: this.selectors.playNext});
    }
  };
```
Tested and working (assuming https://github.com/berrberr/streamkeys/pull/364 is merged).

**Comment by nemchik** [comment]
As a follow up after using this yesterday and today I can say it's working quite well, you can actually skip ads before the countdown reaches 0 and the button is shown.

**Comment by leocaseiro** [comment]
Many thanks, @nemchik

I really appreciate
