### ISSUE TITLE
Standard support for html5 audio

### ISSUE THREAD

**Issue by realdubb** [berrberr/streamkeys#219]
I found streamkeys just wanting an option to play/pause podcasts I play on the web - would it be possible for standard support of any website with audio tags?

To pause/play, fwd/rewind if one track or jump to prev/next if multiple tracks?

I have this a PR https://github.com/berrberr/streamkeys/pull/218 for devchat.tv where I did just that but for one website... can this be extended as a feature to all like websites?

**Comment by berrberr** [comment]
Hmm, I feel like this will be _very_ difficult to get right and there will be a **lot** of problems resulting from this. Will be very hard/impossible to test and handle all the edge cases as well.

I guess the extension is sort of at a point where enough people use it that I am very cautious about adding something like this that has a bunch of unknown consequences :).

For now lets limit the scope keep it on a site by site basis :). Thanks! 👍
