### ISSUE TITLE
Don't show buttons on streaming page of domain

### ISSUE THREAD

**Issue by realdubb** [berrberr/streamkeys#220]
How do you hide the media keys on streaming keys when you're on a non-media page of a website?

for example: (hides media keys)
https://www.youtube.com/yt/press/

vs. (shows media keys)
https://www.youtube.com

I'm not sure if this works all the time or something special has to be done to make this possible. I'd like to do this to a website I want to add.

**Comment by berrberr** [comment]
You can set the `hidePlayer` property on the `BaseController` that you construct to `true`. Example for youtube: https://github.com/berrberr/streamkeys/blob/master/code/js/controllers/YoutubeController.js#L32

Inside the popup there is check if `hidePlayer` is set, and if it is it will only show the site if there is a valid playPause element on the page. The logic is here: https://github.com/berrberr/streamkeys/blob/master/code/js/popup/popup.js#L24
