### ISSUE TITLE
Vk.com handler

### ISSUE THREAD

**Issue by stasusov** [berrberr/streamkeys#224]
Hey.
Thanks for extension! It is very useful.
(**You can see only last comment now, and if it will not be clear, read all the messages**)
I have an issue about vk.com support. The site is not displayed in extension. Soundcloud, for example, works perfectly. I've tried opening different pages, but it doesn't work. Maybe you have disabled support for old design with issue #201 ? Maybe, @ovcharik have made some mistakes in pr #221 .
Unfortunately, new design is in kind of beta-testing and is not available for all users.
I've also tried to add "vk.com" and "vk" to aliases
I'm using ubuntu 14.04 and latest chrome-stable available (51.0.2704.106 (64-bit))
Thanks

**Comment by stasusov** [comment]
Have this in chrome console on loading of page vk.com/audio:
`STREAMKEYS-INFO: Attached listener for  c {siteName: "VK", selectors: Object, oldState: Object, buttonSwitch: false}buttonSwitch: falsehidePlayer: trueoldState: ObjectoverridePlayNext: falseoverridePlayPause: falseoverridePlayPrev: falseplayNext: ()playPause: ()playPrev: ()selectors: ObjectsiteName: "VK"__proto__: Object
VkController.js:1 STREAMKEYS-INFO: Player state change `
Pretty same for soundcloud and, moreover, have methods `playNext()`, `playPause()`, `playPrev()` defined in `c` object for last one. `c.oldState` attributes `canDislike`, `canLike`, `canPlayNext`, `canPlayPause`, `canPlayPrev` are all set to false for VK, but not soundcloud. 
As i said, i can see soundcloud menu in streamkeys, but no menu for vk

**Comment by stasusov** [comment]
I've got some more. Menu for VK is showing only if little player of vk.com (that exist on any page except /audio if song is playing) is expanded. Than, if i trying to switch the track from the streamkeys menu, the player is going to constricted state and menu for VK is hiding again.

So, as i think, the problem is about selectors. 
If you can, add selectors for both little-player (on any page) and full-page player (on sort /audio pages).

Little-player's controls: 
`playPause: "#gp_play",
playNext: ".next_prev > .prev.nav_track",
playPrev: ".next_prev > .next.nav_track",
playState: "#gp_play.playing",
artist: "#gp_performer",
song: "#gp_title"`

Full-page's controls:
`playPause: "#ac_play",
playNext: "#ac_prev",
playPrev: "#ac_next",
playState: "#ac_play.playing",
artist: "#ac_preformer",
song: "#ac_title"`

Fix it, please
Hope this will help and work.

**Comment by ovcharik** [comment]
Hello.

Pull requests #201 and #221 not yet included in the release. Please, try [this build](https://drive.google.com/open?id=0Bze9QgDZTVVsVHo4VGNUbWtnU0E), it should work for both new and old design [vk.com](https://vk.com).

**Comment by stasusov** [comment]
Yes, it works for the buttons enables. Thanks.
But, there is no 'like' button enabled. It can add tracks to user audio collection, as i suggested upper.
And, what is more, this version still has 1.6.0 version, what was a little confusing.

**Comment by berrberr** [comment]
Added in 1.6.1. Thanks @ovcharik :)
