### ISSUE TITLE
Cannot enable any soundcloud

### ISSUE THREAD

**Issue by Nomy1** [berrberr/streamkeys#227]
1. In options, Soundcloud is "enabled" (red background). 
2. I open up Soundcloud.com tab and when I click the Streamkeys icon in my chrome browser, It says no music sites open. 
3. If I click show disabled button, soundcloud appears and I can play, pause, etc.

I tried restarting chrome, updating to newest chrome version, disabling all of my other chrome extensions, but none of this solves the issue.

**Comment by berrberr** [comment]
You have the options page backwards. Red background means disabled, and grey background is enabled. All the sites start enabled by default.

You're not the first one to be confused by this :). I'll add some stuff to try to make the options page more clear.
