### ISSUE TITLE
Small interface artifacts

### ISSUE THREAD

**Issue by maxborowsky** [berrberr/streamkeys#234]
If the plug icon is clicked, once you can see thin white border on right-down:

![screenshot-1](https://cloud.githubusercontent.com/assets/20723033/17246505/44d34688-5595-11e6-8faa-b45c87f34238.png)

If the cursor is moved out, white border disappears partially:

![screenshot-2](https://cloud.githubusercontent.com/assets/20723033/17246577/b5a27032-5595-11e6-9c18-0006fefa6c4a.png)

Only if the cursor is placed over a pop-up plug window, white border disappears completely:

![screenshot-3](https://cloud.githubusercontent.com/assets/20723033/17246684/4f3df266-5596-11e6-9158-6a294c2f287a.png)

**Comment by berrberr** [comment]
Thanks for the report. What OS and chrome version are you using?

It's been challenging to make the popup styles consistent ... Chrome seems to have no consistency across OS's at least with the styling. For example, here is what the popup looks like to me on OSX 10.11.5 with Chrome 51.0.2704.103:

<img width="350" alt="screen shot 2016-08-07 at 12 44 51 pm" src="https://cloud.githubusercontent.com/assets/861000/17463813/ef22abb6-5c9c-11e6-8903-fd57f6694021.png">

**Comment by maxborowsky** [comment]
@berrberr - I use Win 8.1, Vivaldi 1.2.490.43 (latest stable).
