### ISSUE TITLE
Play/pause not toggling to Pause on Deezer

### ISSUE THREAD

**Issue by dr-draik** [berrberr/streamkeys#242]
When playing media in Deezer, the play/pause button (and hotkey functionality) does not toggle to Pause after playing. All other media controls and hotkeys work as expected. i.e. Play, Previous, Next all work correctly.

I have tested StreamKeys on YouTube and all functionality works correctly, suggesting that the problem is specifically related to Deezer rather than being a general issue.

**Comment by spellizzari** [comment]
I observe the same problem here. Developer Tools on Chrome says this:
DeezerController.js:1 STREAMKEYS-ERROR: Element not found for click. .control.control-play

The CSS selector for the play and pause buttons are still right, but Streamkeys fail to detect when Deezer is playing (it always thinks it's in paused mode).

**Comment by spellizzari** [comment]
Digging further. In DeezerController.js, buttonSwitch is set only when the element #loading_bar exists, but here on Deezer it never does. When I force buttonSwitch to true then the Play/Pause toggle works.

Maybe Deezer changed the name of that element in their page? What was supposed to be #loading_bar?

**Comment by dr-draik** [comment]
I have debugged and found the same problem - I agree that is the issue. Deezer must have updated their layout.

**Comment by Gawiga** [comment]
Someone found a way to solution this problem? I'm having this issue too.

**Comment by dr-draik** [comment]
You can patch it for a session as follows:

1. Open dev tools
2. Find DeezerController.js
3. Pretty print the minified code
4. Place a break point at playPause (in Chrome this is currently Line 110: c.prototype.playPause)
5. Press your play/pause button
6. Open the JS console and enter: this.buttonSwitch = true;

The controls will then update as long as the page remains open.

**Comment by berrberr** [comment]
Thanks, yeah looks like Deezer changed their site. Will fix in next release
