### ISSUE TITLE
Double-clicks for google-play-music

### ISSUE THREAD

**Issue by schorsch3000** [berrberr/streamkeys#250]
Hi,
I've configured 3 Buttons in Stream-keys, prev, next and play/pause.
They all work as intended for most sites.
In Google Play Music they all Double-Click.

Resulting in a fast play-stop-play or stop-play-stop wen the play/pause button is pressed and in skip one song if prev/next is pressed.

that happens at work and at home.

in both situations i use linux mint.

Can i do anything to help you out with this issue?

**Comment by fuadsaud** [comment]
I've recently started using GPM and am experiencing that as well. Not sure if has ever worked properly. I'll take a look at the code to see if I can find something.

**Comment by schorsch3000** [comment]
That worked before, i've used it for month without problems.
Thanks for investigating :)

**Comment by berrberr** [comment]
@fuadsaud @schorsch3000 do you have the Google Play Music extension installed as well? That extension will double bind media keys by default causing two commands to be sent.

**Comment by schorsch3000** [comment]
@berrberr yeah, is think i should be ashamed :/
@fuadsaud should we close this? does that fix it for you to?

**Comment by fuadsaud** [comment]
Is it this app you guys are talking about? https://chrome.google.com/webstore/detail/google-play-music/icppfcnhkcmnfdhfhphakoifcfokfdhg?hl=en-US

I'm wondering whether it's possible, and if so, interesting, for streamkeys to check if that app is loaded and disable support for Google Play Music. What do you think?

**Comment by schorsch3000** [comment]
yes, exactly this extension.
I think we can close this issue since it's nocht a streamkeys bug.
@fuadsaud you shozld discuss your feature-request in an seperate issue.
