### ISSUE TITLE
Youtube Previous Video Hotkey

### ISSUE THREAD

**Issue by AlexWolski** [berrberr/streamkeys#253]
It would be convenient to have a "previous video" hotkey for youtube when doing things such as listing to a playlist. A simple way to implement this would be to "go back to previous page" on any youtube tab when the hotkey is pressed.

**Comment by nemchik** [comment]
There actually already is code in place to handle the previous key
https://github.com/berrberr/streamkeys/blob/master/code/js/controllers/YoutubeController.js
I believe this only works in playlists though, it does not go back to previous pages.

**Comment by alecbenzer** [comment]
It'd be nice if it also went back, because 'track forward' always goes forward to the next suggested autoplay video, so then you're able to go forward with track forward but can't go back with 'track back'.

**Comment by nemchik** [comment]
Maybe at https://github.com/berrberr/streamkeys/blob/master/code/js/controllers/YoutubeController.js#L76 you could do something like
```
controller.playPrev = function() {
  if(document.querySelector(this.selectors.playPrev) === null) window.history.back();
  else this.click({selectorButton: this.selectors.playPrev, action: "playPrev"});
};
```
Unfortunately I don't have time to test this, but I think that'll work.

**Comment by nemchik** [comment]
I've experimented a bunch on this and I can't seem to find a working solution. The code I posted above should work, but I don't thing the `window` is actually the targeting the player, but rather the popup (I could be wrong).

Anyway, I've switched to some new logic to account for the new YouTube player

```
  BaseController.playPrev = function() {
    if ($(".ytp-prev-button[aria-disabled='true']") !== null) {
      window.history.back();
    } else {
      this.click({action: "playPrev", selectorButton: this.selectors.playPrev});
    }
  };
```

This isn't working (or I'd make a PR).
