### ISSUE TITLE
Doesn't work with Invincea extension

### ISSUE THREAD

**Issue by canardl** [berrberr/streamkeys#259]
Hi,

My company uses Invincea software on my Windows computer and Invincea Chrome Guest Extension to protect my browser from attacks. To understand, Invincea create a sandbox of my Chrome session to protect my Windows environment. 

Before my company push this new software, streamkeys worked like a charm. Since, when I press skip/resume/pause button, nothing happens.

Sorry for my english, I'm french user.

Regards,

**Comment by berrberr** [comment]
Sorry to hear that, unfortunately nothing that I can do. Sorry!
