### ISSUE TITLE
Spotify player does not work properly

### ISSUE THREAD

**Issue by stepan** [berrberr/streamkeys#263]
When the chrome tab that has spotify web app open is not active, pressing play/pause, previous and next keys either takes several seconds to work or it doesn't do anything at all. If the spotify tab is active, it works as expected.

**Comment by djdmbrwsk** [comment]
+1

**Comment by berrberr** [comment]
Probably fixed in 1.6.4, please re-open if not

**Comment by stepan** [comment]
Thanks @berrberr. It works great now!
