### ISSUE TITLE
Toggle option to only effect currently selected Tab

### ISSUE THREAD

**Issue by strider3029** [berrberr/streamkeys#264]
Hey all, just found this extension and so far finding it very promising.

Main issue for me currently is that I (like most others) live with a ton of tabs open simultaneously with things I plan to 'get back to' eventually - including a pinned tab for both a YouTube channel and Netflix.  So I'll be playing something, or working on my other monitor while I watch/play/pause whichever browser tab I currently have active.

I'd love if we could get support for streamkeys to only affect the currently opened tab.  If I knew JS better, I'd probably try and figure it out myself, possibly by piggy backing the current tab disabling feature (my current work around).

**Comment by fent** [comment]
Came here to ask for this feature and now to show support 👍 

The way I used to do this with applescript (before Chrome disabled them), was to look if the currently active tab of a window had a playing page, such as YouTube, Twitch, Netflix, etc. If it did, then it would affect only that page, if not then it would look at the rest of the tabs.

**Comment by Rohaq** [comment]
Even if this is difficult to figure out, a configurable keyboard shortcut to disable control of all tabs but the current one would be pretty cool.

You could also attach a listener for the affected tab being closed to re-enable control for other tabs when it's gone, too.

**Comment by metaflow** [comment]
@strider3029 would #133 work for you?

**Comment by strider3029** [comment]
@metaflow that would be a nice option as well.  Definitely a worthwhile feature if it's possible.

**Comment by metaflow** [comment]
@strider3029 yea, I am working on it atm. Just wondering if it's OK to close this one after PR landed.

**Comment by strider3029** [comment]
@metaflow I think it would still be a good feature, but I'll leave it to your discretion as someone actively working on the project :)

Thanks for your efforts!
