### ISSUE TITLE
Streamkeys takes priority over media keys on OS.

### ISSUE THREAD

**Issue by Shippage** [berrberr/streamkeys#266]
By default, the Chrome key binds for Streamkeys is set to "Global".

Say I have VLC or Spotify running in a client in the background, it breaks their media key access while Chrome is simply open.

Changing this setting to "In Chrome" fixes this issue, I propose this should be the default option.

**Comment by berrberr** [comment]
The majority of users are looking for a global hotkey solution, so "global" is going to remain the default.

I do wish that Chrome would fix sharing media keys across apps better though :)
