### ISSUE TITLE
Ubuntu Compatibility?

### ISSUE THREAD

**Issue by orschiro** [berrberr/streamkeys#268]
Dear @berrberr,

Thank you so much for this extension!

I have a question. How can I achieve the following:

1. Keep my Ubuntu media keys active. I had to disable them for streamkeys to work on YouTube (see image below).
2. Use my media keys on YouTube with the help of streamkeys. 

How do I do that?

![streamkeys](https://cloud.githubusercontent.com/assets/170947/22546731/84c3c1b8-e93e-11e6-9118-caafeb2a216b.png)

![image](https://cloud.githubusercontent.com/assets/170947/22546748/9a4475f0-e93e-11e6-9cc2-ce683b4ef8e8.png)

**Comment by mahmoudhossam** [comment]
In the keyboard settings shown in the first screenshot, click on the desired shortcut and press backspace to clear it.

**Comment by orschiro** [comment]
Dear @mahmoudhossam,

So back to my original question:

Can I have media hotkey support for streamkeys and Ubuntu at the same time?

**Comment by mahmoudhossam** [comment]
@orschiro You can map streamkeys to different controls and keep your ubuntu bindings.

**Comment by orschiro** [comment]
OK, thank you!

That answered my question. Thus I cannot use my media keys for both Ubuntu and the streamkeys application.

**Comment by mahmoudhossam** [comment]
Not the same bindings anyway.

If your problem has been solved, please close this issue.

**Comment by orschiro** [comment]
Thanks!
