### ISSUE TITLE
Add support for www.driveplayer.com

### ISSUE THREAD

**Issue by saintego** [berrberr/streamkeys#271]
it's player for google drive - www.driveplayer.com

**Comment by saintego** [comment]
I tried to write it, but I have problems to run streamkeys in developer mode to test it.
DriveplayerController.js
`
;(function() {
  "use strict";

  var BaseController = require("BaseController");

  new BaseController({
    siteName: "DrivePlayer",
    play: ".jp-control.jp-play",
    pause: ".jp-control.jp-pause",
    playNext: ".jp-control.jp-next",
    playPrev: ".jp-control.jp-previous",
    mute: ".jp-control.jp-mute",
    buttonSwitch: true,

    song: ".playing.title",
    artist: ".playing.artist"
  });
})();
`

**Comment by shuuji3** [comment]
Hi, I added a Driveplayer support by pull-request(#272) based on your code. 😄

P.S. Some comments on your code:
- The class of control elements is `.jp-controls`, not `.jp-control`.
-  `.jp-play`, `.jp-pause` etc. are the decendants of `.jp-controls`, so we should have put ` `(space) between them like this: `.jp-controls .jp-play`

**Comment by berrberr** [comment]
Added in #272 

Thanks @shuuji3 :)
