### ISSUE TITLE
Brain.fm does not pause

### ISSUE THREAD

**Issue by grinn** [berrberr/streamkeys#273]
The Play button for Brain.fm works, but Streamkeys will not pause it. Here are the reproduction steps:

1. Launch Brain.fm in Chrome and follow the steps to begin playing audio.
2. Click the Streamkeys button. Observe that BrainFM is displayed. Observe that the Play button is displayed and enabled (and not Pause.)
3. Click the Play button. Observe that nothing happens.
4. In your Brain.fm tab, click the Play/Pause button. Observe that the music pauses.
5. In Streamkeys or using your assigned hotkey on your keyboard, hit the Play/Pause button. Observe that the music starts.
6. In Streamkeys or using your assigned hotkey on your keyboard, hit the Play/Pause button again. Observe that the music does not stop.

The issue appears to be caused by the selector in BrainFMController.js. It is using `#play_button.tc_play`. When the content is paused, this button's class is changed to `tc_pause` and so the element is not found. Considering that according to HTML standards, you can only ever have one element with a given ID, a simple fix would be to change this selector to simply `#play_button`.

**Comment by berrberr** [comment]
Merged in #274

Thanks @grinn
