### ISSUE TITLE
[Feature] Embedded youtube

### ISSUE THREAD

**Issue by duranivan** [berrberr/streamkeys#275]
I use Firefox with the add-on ['media keys'](https://www.codesdope.com/python-make-a-list) basically because many websites such as khan academy use some sort of youtube embedded videos, and despite 'media keys' not supporting that specific website still I am able to control the embedded youtube video as Youtube is supported by the add-on. I wonder if this is something that can be accomplished as well in Chrome or it is just possible because of Firefox.

It would be a great if this feature could be added to stream keys as I have to use Firefox mainly because of that add-on. Thanks in advance!

**Comment by arthurcgusmao** [comment]
Why has this issue been closed? I was going to suggest the same. Many websites I use embed Vimeo or YouTube video on their own webpage and I would find it very useful if StreamKeys could be used to control those embedded videos as well. Anyways, congratulations on the great work done so far!

**Comment by cubimon** [comment]
@arthurcgusmao maybe #466 solves your problem?

**Comment by arthurcgusmao** [comment]
Hi @cubimon thanks for your help.

Unfortunately, I cannot find any "Embedded Element" in my Streamkeys configurations:
![image](https://user-images.githubusercontent.com/12454729/51965820-f52cd480-246a-11e9-9146-d1f22edd77d0.png)

Should I do something to make that available? My version of the plugin is 1.7.8, which seems to be the latest.

**Comment by cubimon** [comment]
The #466 PR is merged into master. But it still differs from the version of chrome web store? Maybe a new version hasn't been deployed to the chrome web store since #466. You probably have to build the latest version yourself

**Comment by arthurcgusmao** [comment]
In the Chrome web store? I have just deleted my version and installed it again from the web store but still not embedded element. I will try upgrading apt (I use Ubuntu 16.04) and see if it helps. I want to use it to control an embedded Vimeo element (which currently is not recognized by Streamkeys).

**Comment by cubimon** [comment]
By most current version I meant the master branch, sorry for the misunderstanding

**Comment by arthurcgusmao** [comment]
Oh ok, thanks. I built the master version but unfortunately wasn't able to control embedded elements. I tried putting aliases on the 'Embedded Element' and on 'Vimeo'. On the first case, Streamkeys did not detect anything at all. In the second, I did detect but was not able to actually control the element (play button had no effect). Anyway, thank you very much for your support @cubimon !
