### ISSUE TITLE
Pressing play/pause key results in momentary play/pause

### ISSUE THREAD

**Issue by mountswolmore** [berrberr/streamkeys#278]
When using SK with Google Music, pressing play/pause while music is playing will result in a 0.1 second (brief) pause and music starts playing again. The reverse is true for pressing play/pause while paused. The music will play a brief sound and then pause again. It's like the button is being pressed twice.

Mashing the key a few times will sometimes result in the function working.

**Comment by berrberr** [comment]
You probably have the google play music extension installed which also uses the media keys. Try disabling that extension or changing hotkeys
