### ISSUE TITLE
Plex does not work on my domain without port

### ISSUE THREAD

**Issue by don-mums** [berrberr/streamkeys#279]
When I use Plex on my domain without the default `:32400` port SK does not recognize that I'm on plex website. It's not such a big deal but it's a little bit annoying that I cannot use plex on public facing server on recognizable domain without `:32400` being in the address bar.

**Comment by berrberr** [comment]
Have you tried adding an alias in the options page? You should be able to add an alias for Plex that is just `hostname` without the port and it should work

**Comment by Pbroc** [comment]
Even with alias (192.168.1.14), Plex is not detected correctly.

Beside that the buttons are working under "disabled sites".

Plex server version: 1.5.5.3634
Plex web version: 3.2.1

**Comment by nemchik** [comment]
Are you able to use https://plex.tv/web ?
