### ISSUE TITLE
Streamkeys blocked by Logitech Mouse and Keyboard settings tray

### ISSUE THREAD

**Issue by timdonovanuk** [berrberr/streamkeys#281]
Just a FYI..might want to put it in the FAQ. The Logitech Mouse and Keyboard software loads by default for me and minimises to the windows tray. I was struggling to get Streamkeys working until I thought maybe the Logitech software was intercepting media key calls..I was right.

**Comment by berrberr** [comment]
Thanks for the info :) I'll add to FAQ
