### ISSUE TITLE
Not in webstore

### ISSUE THREAD

**Issue by lost1227** [berrberr/streamkeys#282]
[Error 404](https://chrome.google.com/webstore/detail/ekpipjofdicppbepocohdlgenahaneen) when trying to access webstore page. A search in the webstore yields no results.

**Comment by berrberr** [comment]
Yeah. Google took it down with not explanation or warning yesterday :|. Just for some amusement here is the email they sent:

> Dear Developer,
> 
> Your Google Chrome item, "Streamkeys," with ID: ekpipjofdicppbepocohdlgenahaneen did not comply with our program policies and was removed from the Google Chrome Web Store.
> 
> The Program Policies can be found here: https://developers.google.com/chrome/web-store/program_policies
> 
> If you'd like to re-submit your item, please make the appropriate changes to the item so that it complies with our policies, then re-publish it in your developer dashboard. Please reply to this email for issues regarding this item removal.
> 
> *Please keep in mind that your re-submitted item will not be immediately published live in the store. All re-submitted items undergo a strict compliance review and will be re-published if the item passes review.
> 
> *Important Note
> Repeated or egregious violations in the store may result in your developer account being banned from the store. This may also result in the suspension of related Google services associated with your Google account. All re-submitted items will continue to be subject to Chrome Web Store policies and terms of service.
> 
> Thank you for your cooperation,
> Google Chrome Web Store team

Notice how they don't even say which policies it breaks. Not really sure what to do TBH, I sent them an email but no response yet. It's Google support so I basically expecting the worst.

**Comment by jmcken8** [comment]
That sucks lol

**Comment by berrberr** [comment]
Well Google added it back today without any changes. Still didn't provide any info on why it was taken down, I would guess either it was auto-removed by one of their bots or it was reported for abuse.

**Comment by akrejczinger** [comment]
The extension is down again. Any update?

**Comment by giogziro95** [comment]
@akrejczinger It was taken down again. See #416.
