### ISSUE TITLE
Spotify Web Player is broken

### ISSUE THREAD

**Issue by stepan** [berrberr/streamkeys#283]
Looks like Spotify has recently updated their web app and the ids/classes have been changed for pause, next, previous buttons which has broken the functionality.

**Comment by JackFarrand** [comment]
same issue here

**Comment by wilsonic** [comment]
This is still not working for me in 1.6.4 on MacOS El Capitan Chome Version 56.0.2924.87 (64-bit). I tried reinstalling.
