### ISSUE TITLE
media buttons on Logitech keyboard don't function

### ISSUE THREAD

**Issue by AddaxSoft** [berrberr/streamkeys#289]
I have the logitech K520; I can't seem to get the media buttons to work with the extension. 
Other shortcuts work (e:g ctrl+>) globally

When I click on the media buttons while setting the shortcut nothing happens.

![image](https://cloud.githubusercontent.com/assets/6898938/23826292/eeb59ba0-0699-11e7-84aa-405f03d6400f.png)

**Comment by AddaxSoft** [comment]
## Update:

I debugged the problem using javascript / jquery and apparently the problem is Logitech's own SetPoint software.

I have this version:
- Software Version: 6.67.83

the solution to this issue for now is to close SetPoint

**Comment by berrberr** [comment]
Cool thanks, I can add to FAQ
