### ISSUE TITLE
How to implement player which is available on multiple URLs?

### ISSUE THREAD

**Issue by siegy22** [berrberr/streamkeys#292]
Hey there!

First, great job doing this, I really love the extension! (although I can't get it to work with my bluetooth headphones controls somehow 😐 )

In the README I saw that when I create a new controller, that I need to provide a URL, where the player can be used.

Here's the thing: I've got a Synology NAS which has an application called [Audio Station](https://www.synology.com/en-us/dsm/app_packages/AudioStation). I would love to control this player using streamkeys. The problem is, any synology NAS can be reached with different URLs because you can access it from your local network (let's say private IP or just the hostname) plus with DDNS from the internet.

So what do you think is the best solution here? I think to let the user set an alias is the best here?

And what's the default URL which is preset? I think https://www.synology.com/en-us/dsm/app_packages/AudioStation would be a good start?

**Comment by berrberr** [comment]
Streamkeys actually has alias support built in :)

On the options page you can set an alias (hostname portion of url) for a site and it will append that to the url check function here: https://github.com/berrberr/streamkeys/blob/master/code/js/modules/Sitelist.js#L254

Hopefully that is what you are looking for?
