### ISSUE TITLE
Spotify completely stopped working

### ISSUE THREAD

**Issue by Inverified** [berrberr/streamkeys#295]
Spotify Web Player is no longer responsive to any of the media keys for me on update 1.6.5, while all other sites have remained working.

**Comment by moshfeu** [comment]
Same for me on mac.

**Comment by funkybaboon** [comment]
I've made a working fork until this is fixed in the official repo
https://github.com/funkybaboon/streamkeys

**Comment by moshfeu** [comment]
@funkybaboon Thanks! Works for me.

**Comment by berrberr** [comment]
Thank you @funkybaboon . Can you please take a look at #300 and confirm if it's working for you?

Also, closing in favour of #286
