### ISSUE TITLE
Add support for Koel?

### ISSUE THREAD

**Issue by adriel** [berrberr/streamkeys#296]
Any plans to [add support](https://github.com/phanan/koel/issues/130) for [Koel](https://github.com/phanan/koel)?

Live demo page [can be found here](http://demo.koel.phanan.net/) for anyone interested.

**Comment by shuuji3** [comment]
Hi @adriel, 

I can write a new controller for Koel. But I don't know which URL should we specify for this controller.

Is every Koel always have `koel.phanan.net` in the URL or the URL changes depends on the server?

**Comment by adriel** [comment]
The url will never be koel.phanan.net, unless you're using the demo site, it's always a custom url after setting up your koel server.

**Comment by shuuji3** [comment]
Thank you adriel! I didn't notice Streamkeys has the alias feature. 😅
Then, my code (#312) should work well in any custom Koel server.
