### ISSUE TITLE
Add port support?

### ISSUE THREAD

**Issue by heylookltsme** [berrberr/streamkeys#299]
I was wondering if it would be worth it to add support for ports in the site URLs. If someone is running more than one self-hosted music server on the same machine, then the two sites will have the same URL (probably just an IP address), but different ports. It'd be neat if you could specify a port for URL aliases.

**Comment by berrberr** [comment]
You can do this already -- go to the extension options page (popup player has a shortcut), find the site you want and click `aliases`. From there you can add different hostnames with/without ports to inject different controllers into.

One bug that I actually just discovered from making sure that this works is that you need to add a trailing `/` to your alias if your alias ends in a port number (for example an alias of `localhost:3000` won't work, but `localhost:3000/` will 🙈)

That bug happens from a misconstructed regex / Chrome returning urls with trailing slashes from it's tab api (if you're interested, the regex to check what urls to inject controllers into happens here: https://github.com/berrberr/streamkeys/blob/master/code/js/modules/Sitelist.js#L22-L29)

Hopefully that is what you were looking for?

**Comment by heylookltsme** [comment]
Oooh yes, this is exactly what I was looking for. It didn't seem to be working for me yesterday, but maybe I had a trailing slash in there. I don't remember. I'll try again today and report back!

**Comment by heylookltsme** [comment]
Hmmm it doesn't seem to be working for me. My subsonic alias works when it's just the IP address and it doesn't work when it's the IP address and the port. I'm using the actual IP, not `localhost` since subsonic is running on a server on my network, not the computer I'm using with streamkeys. Maybe that's the issue? 

Thanks for your help!
