### ISSUE TITLE
Recently having to click Play/Back/Next multiple times

### ISSUE THREAD

**Issue by ahainen** [berrberr/streamkeys#305]
Hi - I use StreamKeys for Soundcloud and Youtube primarily. 1.6.6. Chrome 57.0.2987.133, 2016 Macbook Pro with TouchBar.

Recently, I've been having to click Play/Back/Next multiple times for it to work. This has been happening with me with Soundcloud & Youtube, when both tabs are open, or when just one of them is open. I've uninstalled/reinstalled StreamKeys, still no dice. Let me know if I can provide more info.

**Comment by nemchik** [comment]
Can you close all tabs, then open a music player you have a problem with, then open the developer console using `Ctrl + Shift + j` and then press a media key and tell us if there are any errors in the console?
