### ISSUE TITLE
New Spotify Web Player not working

### ISSUE THREAD

**Issue by fidelc** [berrberr/streamkeys#307]

**Comment by nikojii** [comment]
`<div class="player-controls__buttons">
<button class="control-button spoticon-shuffle-16" title="Ota satunnaistoisto käyttöön"></button>
<button class="control-button spoticon-skip-back-16" title="Edellinen"></button>
<button class="control-button spoticon-pause-16 control-button--circled" title="Tauko"></button>
<button class="control-button spoticon-skip-forward-16" title="Seuraava"></button>
<button class="control-button spoticon-repeat-16" title="Ota uudelleentoisto käyttöön"></button>
</div>`

**Comment by nikojii** [comment]
```html
<div class="player-controls__buttons">
    <button class="control-button spoticon-shuffle-16" title="Ota satunnaistoisto käyttöön"></button>
    <button class="control-button spoticon-skip-back-16" title="Edellinen"></button>
    <button class="control-button spoticon-pause-16 control-button--circled" title="Tauko"></button>
    <button class="control-button spoticon-skip-forward-16" title="Seuraava"></button>
    <button class="control-button spoticon-repeat-16" title="Ota uudelleentoisto käyttöön"></button>
</div>
```

**Comment by jay-zhu** [comment]
It seems spotify change the class name again. Right now it changes to .spoticon-*-16

**Comment by jay-zhu** [comment]
@berrberr , should we change to something like button[class*="spoticon-play"] in SpotifyController.js?

**Comment by berrberr** [comment]
Should be fixed now
