### ISSUE TITLE
Ubuntu 16.04 compatibility issue? 

### ISSUE THREAD

**Issue by alirzsedghi** [berrberr/streamkeys#310]
Hi, 
is there any compatibility issue on ubuntu ? the keys work inside chrome but not global

**Comment by berrberr** [comment]
Might be a bug with chrome, you can try and see if there is anything at the chrome issue tracker: https://bugs.chromium.org/p/chromium/issues/list

Nothing can be done at the extension level to fix this so closing issue

**Comment by zchen24** [comment]
@sedghi I believe it is a global shortcut key issue. In Keyboard / Shortcuts / Sound and Media, disable Media key related shortcuts should fix this issue.
