### ISSUE TITLE
Airpods support?

### ISSUE THREAD

**Issue by ldiqual** [berrberr/streamkeys#311]
Hey there! Airpods have the ability to play/pause by double tapping on one of them. However it doesn't seem to trigger the media pause key in Chrome. Is there a workaround to get them to work? Can I help in any way?

**Comment by berrberr** [comment]
We can't do anything about this at the extension level, media key interaction is handled by the browser.

Your best bet is to report a bug to the Chrome team https://bugs.chromium.org/p/chromium/issues/list

I hope it can get fixed!
