### ISSUE TITLE
Play/Pause Not Toggling Correctly for Google Play Music

### ISSUE THREAD

**Issue by mguvu** [berrberr/streamkeys#314]
Hello! It appears that even with the latest version of streamkeys [google play music](https://play.google.com/music/listen#/home) play/pause doesn't function. I have the priority set at 2 but when I go to the site and press play/pause I am noticing the play/pause button quickly toggles but then toggles back. So it's like the toggle is double toggling.

- Noah

**Comment by nemchik** [comment]
I can't replicate this issue. Can you look at the bottom of chrome://extensions/ and click Keyboard Shortcuts and see if you have anything specific to Google Play Music in there? If you do have specific hotkeys that say they are setup for Google Play Music then you need to either remove them or disable Streamkeys from controlling Google Play Music.

**Comment by berrberr** [comment]
@mguvu you probably have the google play extension installed. Remove it or change the default hotkeys and it should be fixed
