### ISSUE TITLE
TravisCI connection problems.

### ISSUE THREAD

**Issue by michaelblyons** [berrberr/streamkeys#315]
Both my PR and #312 have the same problem with Travis where it [can't download packages.][1] Was there a change to infrastructure or proxy settings between 4/21 and 4/29?

[1]: https://travis-ci.org/berrberr/streamkeys/builds/228726476#L254

**Comment by berrberr** [comment]
Thanks -- Travis was running a very old node version. Updating it seemed to do the trick and builds are working again
