### ISSUE TITLE
Little bug with new Youtube design

### ISSUE THREAD

**Issue by maxborowsky** [berrberr/streamkeys#318]
If new Youtube design (https://www.youtube.com/new) is enabled, Streamkeys does not display name of active track. Google Chrome 58, Windows 10 64-bit.

**Comment by nemchik** [comment]
I will look into this after https://github.com/berrberr/streamkeys/pull/328 has been merged (or closed).

**Comment by devkhan** [comment]
Maybe unrelated, but the next button also doesn't work in the new UI.
