### ISSUE TITLE
Multiple sites open at the same time

### ISSUE THREAD

**Issue by jpinnekamp** [berrberr/streamkeys#322]
Hi,

I really like the extension, as I mostly get my music through youtube.
One issue I found, is that when I have multiple youtube tabs open at the same time, play/pause toggles all of them, i.e. whats paused plays and what's playing pauses. This can also lead to multiple tabs playing at the same time.

I've never written a chrome extension, but from what I can see in the source code it seems that each tab basically has its own controller running independently from others.
Can it be adapted easily to:
- Ensure only one tab is playing
- If one tab is playing and one tab is paused, pause the playing one and keep the other one paused
- if all tabs are paused, only play one of them, based on some rule, e.g. most recently playing?

Thanks for any advice

**Comment by bsinky** [comment]
One thing you could do right now, there's a disable button in the Streamkeys dropdown you can toggle on/off.  When a site is disabled, the media hotkeys should have no effect on it.  So if you disable a site while it's paused, your Play/Pause key on your keyboard will affect all the non-disabled sites only.

![image](https://user-images.githubusercontent.com/5004786/27155612-377febea-511f-11e7-906c-12a454c2f567.png)

Using that, you might be able to get what you're looking for.  As for a more automatic solution, I can't answer that question.

**Comment by Wizek** [comment]
I'm also interested in a solution to this.

1. Could be as simple as automatically disabling every new open site (e.g. for when I have lots of YouTube videos open), so I can manually enable just one of them.
2. Or more advanced, like only controlling the player that was playing the most recently.
