### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by michaelblyons** [berrberr/streamkeys#324]
Can you `git tag` the versions you publish with their version number so that they show up on [the releases page?](https://github.com/berrberr/streamkeys/releases) I currently have v1.6.7, but it is unclear what code it does or doesn't include.

Thank you!

**Comment by michaelblyons** [comment]
I found the commits. I don't quite have a script that does the tagging, yet. 😉 

```sh
git log --oneline --grep='Bump to ' |
    sed 's/^\([0-9a-f]*\) .* \([0-9]*\.[0-9]*\.[0-9]*\).*/\1 v\2/'
```

**Comment by berrberr** [comment]
Yes good idea! I will do this going forwards
