### ISSUE TITLE
Suggestions: Improve Enabled Sites UI with Filter and Sort

### ISSUE THREAD

**Issue by JohannesMP** [berrberr/streamkeys#340]
While supporting tons of sites is great, with more than 110 sites and growing, a few changes could be made to improve the experience of managing Enabled Sites in the extension's options.

Here are a few suggestions that would help, listed in order of most to least beneficial:

### 1. Filter: *A search field to filter what sites are visible*
  - A 'search' or 'filter' text field at the top of the page, where any text typed would instantly filter the list of all enabled sites. Should display info on how many results match the provided string, example: ("filtered 5/112 sites").
  - Searching should be instant, based on the search string entered, without requiring the user to hit enter or click a search button.
  - Searching should consider a site's name, any provided aliases, and (optionally) any keywords/tags that make sense for the site ("Google" for youtube, tags like `video`, `radio`, `streaming`, etc, Specific languages, etc.)
  - Minimal: Ignoring case, filter out any site that does not contain the exact string entered.
  - Bonus: Support fuzzy searching, so for example searching for "Radio" would still return "Rdio" as a result, "ytbe" would still match "Youtube", etc. 
    - I would recommend an implementation similar to what [Sublime Text](https://www.sublimetext.com/) uses, where each entry is assigned a score based on how well it matches the provided string, and it is up to the implementation how high a score needs to be to be displayed.
    - [This blog post](https://blog.forrestthewoods.com/reverse-engineering-sublime-text-s-fuzzy-match-4cffeed33fdb) discusses reverse-engineering it and the javascript source code is [on github](https://github.com/forrestthewoods/lib_fts/blob/master/code/fts_fuzzy_match.js).
  - Full regex support would be overkill, and unnecessary with good fuzzy search.

### 2. Sort: *Ability to sort displayed sites by priority*
  - Sorting would operate on the result of the current search filter (default is empty, so all sites visible).
  - It would be useful to sort by priority, for example with a button with 3 states (`unsorted`, `sorted(asc)`, `sorted(desc)`).
  - Having the option to simply 'hide disabled' would be nice as well, but optional.
  - Bonus: the current sort state is stored and applied whenever 'Enabled Sites' is viewed.

### 3. Compact View: *A table view alternative to the current grid*
  -  It would be nice to have the option to switch from a grid view to a more compact table view where each site takes up single row, and each attribute has a column that can be sorted by.
  - This is fairly low priority, as a good implementation of recommendations 1 and 2 will make viewing the large number of sites easier, but it would still be a nice-to-have

-----

While probably overkill, for a convenient, dependency-free library for sorting/filtering I'd recommend looking at something like [MixItUp](https://www.kunkalabs.com/mixitup/).

**Comment by berrberr** [comment]
@JohannesMP thanks for the suggestions, some of these are really great ideas :)

I have been meaning to get around to refreshing the options page but have been too busy.

Another problem people have is that the enabled / disabled state of sites is confusing (its done by colour now, red = disabled). Some people will install the extension and then go to options page and think that they are enabling the sites and actually disable them. So I want to change the layout of the actual site boxes as well. Maybe the table view will make it less confusing.
