### ISSUE TITLE
Coursera : Pressing play/pause when viewing a video in a section will jump to first video of playlist instead of playing/pausing current video. (happens after first video is marked as watched by green tick icon)

### ISSUE THREAD

**Issue by PraveenMuthu22** [berrberr/streamkeys#341]
Works fine when watching playlists in youtube. I have only experienced this issue with Coursera.

For example imagine there are 3 sections for Week 1
S1, S2 and S3

While the first video of any section is not marked as watch (Green icon with a tick appears when you fully watch a video) the play/pause works fine.

For example, S1 has three videos v1, v2 and v3. Initially when none of the videos are completely watched play/pause button works fine.

Now completely watch v1. Just go click the end of the video and make the green tick icon appear.

Now try any of the videos  v2 or v3. When play pause is pressed, you are redirected to the first video of the section v1 rather than playing/pausing current video.

Please fix this bug since this extension is immensely useful in Coursera. 

[Video ](https://www.youtube.com/watch?v=bHeFbFz1vr0)documenting the issue.

[Example 2](http://imgur.com/a/kqUPZ)
Here the last video (named final remarks) of topic knapsack is completely watched. So, if I press play/pause while watching any other video under the topic, (eg- problem overview) it would jump to the final remarks video.

**Comment by PraveenMuthu22** [comment]
A video documenting the issue.
https://youtu.be/OqAf119ZgyY

**Comment by Nephiel** [comment]
I am experiencing this same issue.  

In addition, Stop and Prev/Next keys do nothing in Coursera. I assume this is because there are no buttons in the player to hook into:
`STREAMKEYS-ERROR: Element not found for click. [data-track-component='item_side_nav_next_lession']`

**Comment by PraveenMuthu22** [comment]
Also sometimes playing play/pause button on Coursera does nothing at all. (not even jumping to the first video in topic as explained above)

[video showing the issue](https://www.youtube.com/watch?v=6BZl-cOdtEI&feature=youtu.be)

**Comment by MilitaryCheese** [comment]
I’m also experiencing the same issue mentioned here.
