### ISSUE TITLE
Plex Web v3.17.2 broken

### ISSUE THREAD

**Issue by JimboMonkey1234** [berrberr/streamkeys#344]
Plex Web was updated today and play/pause no longer works.

See update 3.17.2 on the forums: https://forums.plex.tv/discussion/46075/plex-web/p11

**Comment by painfulsedative** [comment]
I am having the same issue - hope you can fix it up Alex!

**Comment by cdlenfert** [comment]
forward and back are also non-functional. Thanks for any help.

**Comment by kingbobski** [comment]
+1 No buttons seem to do anything

**Comment by tttttx2** [comment]
can confirm the issue.

**Comment by ol-smaug** [comment]
I am having the same issue as well.

**Comment by shnizmuffin** [comment]
Looks like Plex decided to style their components with JavaScript _because reasons_.

The selectors probably have to target titles now e.g. `button[title=Play]` because who knows what the compiler will decide to suffix `PlayerIconButton-playerButton-1DmNp IconButton-button-2FVq6` with next.

**Comment by JimboMonkey1234** [comment]
Thought I'd try doing this myself, got this code:

```
  new BaseController({
    siteName: "Plex.tv",
    play: "button[aria-label='Play']",
    pause: "button[aria-label='Pause']",
    playNext: "button[aria-label='Next']",
    playPrev: "button[aria-label='Previous']",
    mute: "button[aria-label='Mute Volume']",

    song: "a[role='link']",
    buttonSwitch: true
  });
```

But still couldn't get play/pause to work. StreamKeys finds the buttons, but can't click them. I tried clicking them myself (using jQuery and `.click()`) but still nothing. I don't know what mechaism they're using for pause/play.

Then I found this thread, so this isn't just a StreamKeys problem: [Media Keys Not Working](https://forums.plex.tv/discussion/282558/media-keys-not-working)

**Comment by saloughrey** [comment]
That plex forum thread was created by me and forgot I was actually using StreamKeys and I can't figure out how to edit that post to delete it.  So it is a StreamKeys issue.

**Comment by timdorr** [comment]
@JimboMonkey1234 They have an event listener on document. It's a really weird setup. I think we have to provide an event.target to get it to pick up. I'm not sure why it's trying to track events globally, but that's what they appear to be doing...

**Comment by timdorr** [comment]
Got a fix, I think! I'll try to package it up tonight and then submit a PR.

**Comment by cdlenfert** [comment]
Can someone tell me how to apply this latest version with the fixes for Plex web? I've tried downloading the git repo and installing the extension manually (which looked like it worked after editing the manifest for "name" and "version" however the extension was non-functional. Thanks for any feedback.

**Comment by JimboMonkey1234** [comment]
Worked for me. Odd that you had to edit the manifest, I just built it and loaded unpacked-dev.

If you had changed the hotkey options you'll have to do that again since it resets them.

**Comment by painfulsedative** [comment]
I removed the extension and redownloaded it, thinking it was posted as being updated on the chrome store... problem still exists.  so I guess it hasn't been?

**Comment by JimboMonkey1234** [comment]
@painfulsedative it sounds like you didn't build the extension. See the readme, which says you need to run:
```
npm install
grunt dev
```
Which will create the extension in `build/unpacked-dev`.

**Comment by timdorr** [comment]
@painfulsedative The latest version on the Chrome Store is still 1.6.7: https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen?hl=en Any version higher than that should have this fix, whenever @berrberr can publish it.

**Comment by Tito1337** [comment]
I was happy to see this bug so promptly solved here. But the selection by aria-label only works if Plex is used in English... The aria-labels are indeed translated with the interface.

I don't know if we should open another bug or reopen this one.

**Comment by timdorr** [comment]
@Tito1337 That's good to know. We can probably switch to a partial attribute match. They have hashed class names, but you can still match on `[class^= button-play-]` (or whatever it is).

**Comment by Tito1337** [comment]
@timdorr I had great success with your suggestion, I've made a pull request #350

**Comment by saloughrey** [comment]
Hey how can I get this update?

**Comment by berrberr** [comment]
Hi everyone, v1.7.0 is released with this fix in it. Chrome should start propagating the update to you soon.

Big thanks to @timdorr and @Tito1337 for the fixes!!

**Comment by painfulsedative** [comment]
wooooo many thanks to all involved for getting this resolved so quickly :)

**Comment by ol-smaug** [comment]
Yes, thanks so much to everyone involved!
