### ISSUE TITLE
plex's ui got an update and no longer works

### ISSUE THREAD

**Issue by kylemontmont** [berrberr/streamkeys#353]
please fix plex

**Comment by notnicecream** [comment]
Same thing is happening for me, plex shows up in the streamkeys but all of the buttons don't work anymore.

**Comment by cdlenfert** [comment]
If you're on version 1.7.0 of the StreamKeys extension that just released a couple days ago, you should see Plex working again. I'm having an issue however where my hotkeys are not global and only work if the Plex window is in focus.

**Comment by nemchik** [comment]
This is a pretty oddball issue. I can confirm 1.7.0 does NOT work with the plex.tv site. Further, I can't send `click()` to elements in chrome's JS console, so I can't even get the controller working.

**Comment by cdlenfert** [comment]
@nemchik I think the oddball issue was user error on my part. I have been able to control the Plex interface using 1.7.0 and can do so on the latest server update with the following notes under "what's new": (Web) Updated Plex Web to 3.20.8

**Comment by nemchik** [comment]
Ok, apparently I was having a browser issue or something, I reloaded chrome and was able to get 1.7.0 working with plex.tv with no other changes.

I think this could be closed.
