### ISSUE TITLE
Google Play Music registers commands twice

### ISSUE THREAD

**Issue by taangle** [berrberr/streamkeys#368]
On multiple computers I have had the issue of Google Play Music registering commands twice. For example, if I press pause/play, the song pauses and then immediately begins playing again. Or when I press skip, it skips two songs ahead instead of one. This happens only when using the hotkeys directly from my keyboard.

**Comment by nemchik** [comment]
Try disabling the Google play music controller in Streamkeys settings, then see if hotkeys still work.

If yes: you have another extension installed that also controls Google play music (there is one published by Google that looks like an extension but it's just called Google play music)

If no: there might be an actual issue with streamkeys. Does this happen with any other player for you? YouTube? Spotify? Etc?

**Comment by taangle** [comment]
Sorry, I should have updated. I realized that it is because Google Play Music already supports hotkeys natively, so it must have been getting the commands twice. Disabling Streamkeys for Google Play Music makes it work perfectly.

**Comment by berrberr** [comment]
Great :)
