### ISSUE TITLE
How to add controller if the play, pause buttons are JavaScript commands

### ISSUE THREAD

**Issue by fishfishfish2104** [berrberr/streamkeys#370]
I've been trying to figure out how to add a site to streamkeys I've been writing up a controller file that looks like this 
```
;(function() {
  "use strict";

  var BaseController = require("BaseController");

  new BaseController({
    siteName: "UMS",
    play: "player.unpause()",
    pause: "player.pause()",
    playNext: "next()",
    playPrev: "prev()",
    buttonSwitch: true
  });
})();
```
I know this doesn't work but I don't know how to add the play, pause, next and prev commands to it properly I see in other controller files there look something like this 
` play: "div#play.FL.pe-true",`
or
`playPause: ".ytp-play-button",`
but I don't know what that is referring too
sorry i'm bad at JavaScript and node but I thought i might try :( too hard for me
thanks for the help

**Comment by bsinky** [comment]
So the `play: "div#play.FL.pe-true"` is just a CSS selector that tells Streamkeys how to find the given button on the page (in this case, the play button) so that it can simulate a click, just as if the user had clicked the button.  Same for `play-pause`, and so on.

In light of that, I'm confused as to why the only way to play/pause a player would be through javascript commands.  Are there no buttons for playing/pausing/next/previous in the UI for the site you're adding?

**Comment by fishfishfish2104** [comment]
the UI I'm using is the Universal media server web interface and the play/pause button is built into the player but the next/previous buttons arn't here's a screenshot 
![screenshot 2017-10-06 at 12 07 50 pm](https://user-images.githubusercontent.com/16485618/31256439-1720a136-aa8f-11e7-92ed-4df1522a64b5.png)

all of that is one element in html except for the next/previous buttons at the bottom and i couldn't find any css elements with somthing that relates to it 
thanks for clearing up what the selectors are if you want a copy of the css and/or the html I can get them

**Comment by fishfishfish2104** [comment]
i've tried to get the css selectors for the buttons but they are in the shadow dom so queryselector won't be able to find them any way if you know of a way around this please tell

**Comment by fishfishfish2104** [comment]
never mind i just added a button to the site as im the host i realised that it wasn't realy worth the effort of figuring out how to get queryselector to work in shadow dom so im going to close it
