### ISSUE TITLE
[Feature Request] Firefox support through WebExtensions

### ISSUE THREAD

**Issue by nermolov** [berrberr/streamkeys#373]
Firefox is now coming up to speed with chrome on the WebExtensions api and media keys are now supported through it: https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/commands

I tried running streamkeys in its current state but got quite a few issues with scripts not loading and CSP violations.

It seems like this port would be relatively easy but I'm not familiar enough with streamkeys's architecture yet.

**Comment by ppowalowski** [comment]
Same here! Used Foxified Extension to run it inside the new firefox and it even worked! Unfortunately the keybindings don't work as expected so the only working function is play/pause - confirming your suggestion about your port being relatively easy.

Please make it work :) I really enjoy the new firefox.

**Comment by JackHack96** [comment]
I'm joining the queue :+1:

**Comment by ppowalowski** [comment]
Since Firefox is cool again it's worth it B-)

**Comment by rootyElf** [comment]
I second that.

**Comment by X-Ryl669** [comment]
Firefox at that time does not support `global` keys, so there is no reason to expect anything "kindof" working right now. Sure, if the current tab is in focus, you can use Play/Pause button to play or pause, but it's kinda useless in that case (just press "spacebar", don't need an extension). When Firefox supports `global` keys, it'll rock!

**Comment by alike03** [comment]
Yeap unfortunatly [Firefox does not have the support](https://developer.mozilla.org/de/Add-ons/WebExtensions/manifest.json/commands#Browser_compatibility) atm but in the future they will surely implement it.

**Comment by FoxxMD** [comment]
Dang this is the only thing preventing me from switching to FF full time :(

**Comment by berrberr** [comment]
Until Firefox supports global commands I don't see the point in porting this over, since IMO global hotkeys are the best feature (and why this extension was made in the first place :)). Without global commands the hotkeys will only work if the browser is in focus.

**Comment by Smile4ever** [comment]
The support for global keyboard shortcuts is tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1411795
