### ISSUE TITLE
chrome disable other apps listening to media keys

### ISSUE THREAD

**Issue by romaad** [berrberr/streamkeys#376]
if i'm opening chrome with no music sites and have my music app in background, spotify desktop app for example, pressing media keys will not trigger any actions in spotify until chrome is closed.

**Comment by bsinky** [comment]
This is an issue with Chrome.  For a potential workaround, you can change your chrome Keyboard Shortcuts settings (go to chrome://extensions, scroll the bottom, bottom right link "Keyboard Shortcuts") from "Global" to "In Chrome" for each of the media keys.

See issue #80 for a discussion of this.

**Comment by awan1** [comment]
+1 this worked for me
