### ISSUE TITLE
Youtube player has changed, streamkey doesn't seem to work anymore.

### ISSUE THREAD

**Issue by srivest** [berrberr/streamkeys#383]
I've noticed my instance of streamkey has stopped working with youtube. Upon investigation I found that the youtube player seems to have changed, for instance, on a watch later playlist the "next" button isn't in the player anymore. 

Any idea on how to resolve this?

Thanks, great tool.

**Comment by jeffvandyke** [comment]
This issue can be closed, I think. I saw a pull request for the new YouTube UI was merged in a while ago, and I'm having no problems with streamkey on YouTube.

**Comment by srivest** [comment]
Affirmative

**Comment by leocaseiro** [comment]
@srivest you could close the issue.

**Comment by srivest** [comment]
Done

**Comment by srivest** [comment]
Done
