### ISSUE TITLE
Add support for Libresonic

### ISSUE THREAD

**Issue by protist** [berrberr/streamkeys#385]
It'd be great if this add-on could support Libresonic (the open-source successor to Subsonic). The html element for the play button is
```
<div id="jwplayer_jwplayer_controlbar_playButton" style="height: 100%; position: relative; display: block; float: left; background: rgba(0, 0, 0, 0) url(&quot;data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABUAAAAYCAYAAAAVibZIAAAANUlEQVR42u2RsQkAAAjD/NTTPaW6dXLrINJA1kBpGPMAjDWmOgp1HFQXx+b1KOefO4oxY57R73YnVYCQUCQAAAAASUVORK5CYII=&quot;) repeat-x scroll left center; width: 21px; cursor: pointer;">&nbsp;</div>
```
back is
```
<img src="icons/default_light/back.png" alt="" onclick="onPrevious()" style="cursor:pointer">
```
and forward is
```
<img src="icons/default_light/forward.png" alt="" onclick="onNext(false)" style="cursor:pointer">
```

**Comment by Camron** [comment]
Would you still want this or did you move to Airsonic?

**Comment by protist** [comment]
Huh, I didn't realise Libresonic got reforked! Thanks for the update, I'll migrate again!

As far as this ticket goes, I'm actually unlikely to use either via the browser. I found that the pause between tracks was too irritating for me, so I cloned my collection locally instead. Feel free to close this issue if it's not a priority any more. Cheers.
