### ISSUE TITLE
Cannot build extension

### ISSUE THREAD

**Issue by cdlenfert** [berrberr/streamkeys#387]
How are people able to build this? I'd like to add support for the Volumio client but cannot build the extension locally to test my controller code.

node -v v0.10.29 npm -v 1.4.14
Pastebin https://pastebin.com/gbdpu8rJ

**Comment by bsinky** [comment]
I'm able to `grunt rel` and `grunt dev` just fine on my Windows 8.1 machine, `node v8.9.1` and `npm 5.5.1`

I think `node v0.10.29` is fairly old, right ([this listing](https://nodejs.org/dist/v0.10.29/) makes me think it was released in 2014)? You might try updating to the LTS release of `node`, which is apparently `8.9.3` according to [their website](https://nodejs.org/en/).

**Comment by cdlenfert** [comment]
Thank you, new to this and wasn't aware how outdated these were on my system.

**Comment by berrberr** [comment]
Thanks @bsinky
