### ISSUE TITLE
Fedora - GNOME Shell - Keyboard Shortcut needs to be disabled in order for SK to work

### ISSUE THREAD

**Issue by ndroftheline** [berrberr/streamkeys#389]
Hey just a quick note, I discovered that you have to disable the default play/pause keyboard shortcut in Fedora Workstation (using Gnome Shell) in order for SK to 'hear" the media key on my keyboard. Had already opened this window to complain about it when I set the keyboard shortcut in Settings > Devices > Keyboard for audio play/pause to some random combination instead of the hard button on my USB keyboard (a logitech job). Once I'd reassigned it, SK started picking up the button perfectly. Thanks for such a great extension (: +1:

**Comment by berrberr** [comment]
Interesting, thanks. This is an issue with Chrome though :)
