### ISSUE TITLE
Pressing play/pause once could result in multiple presses

### ISSUE THREAD

**Issue by fgblomqvist** [berrberr/streamkeys#390]
If I press play/pause on Google Music it will fail at least half of the times because it thinks I pressed the button twice. This happens on both my laptop keyboard and my external keyboard.

I opened the dev console and took the following screenshot:
![screenshot from 2017-12-18 00-58-51](https://user-images.githubusercontent.com/649260/34085339-5d5b186e-e38f-11e7-8fce-59e306d704fa.png)

The times it failed were the times it said "Player state changed" twice.
Let me know if there's anything else I can do.

**Comment by nemchik** [comment]
Do you by chance have the Google music extension installed in chrome?

**Comment by fgblomqvist** [comment]
Oh god, I did have that one installed. It's been ages since I installed it (but it stuck due to profile syncing) so forgot about it. Removing it fixed the issue. Thank you!
