### ISSUE TITLE
Add support for BBC Player

### ISSUE THREAD

**Issue by withoutclass** [berrberr/streamkeys#392]
It would be great if you could add support for the BBC radio player.  Here is a url with an example: http://www.bbc.co.uk/programmes/b09jj651

**Comment by dsedivec** [comment]
Streamkeys does support BBC's radio player, but I think maybe something is broken?  If I disable BBC then visit the above URL, Streamkeys tells me that BBC is disabled.  However, with BBC enabled in Streamkeys, it just says "no music sites open".

Chrome 65, Streamkeys 1.7.2
