### ISSUE TITLE
Why volume keys are global?

### ISSUE THREAD

**Issue by rhazor** [berrberr/streamkeys#396]
Hello, this addon works fine, but why the volume keys are global?

E.g. when in-game trying to lower volume, it lowers the volume on Mixcloud and volume in-game.

My keyboard is Cooler Master Devastator, it has keys Stop/Play/Pause/Back/Forward and Volume keys.

All keys are locked to Chrome except volume. Would be nice if e.g. volume keys lowered volume from Mixlcoud's player volume bar and not main system volume. Cheers.

**Comment by berrberr** [comment]
Volume change is not supported. Also, Chrome doesn't use volume keys as valid hotkeys so there is no way to override the default behaviour.
