### ISSUE TITLE
Streamkeys hijacks media keys when enabled

### ISSUE THREAD

**Issue by avamsi** [berrberr/streamkeys#397]
When Streamkeys is enabled, I can't use media keys to control other applications (Spotify, for example) on macOS High Sierra. Is this the intended behaviour? I feel like Streamkeys used to not hijack these keys before?

**Comment by Syther101** [comment]
Also experiencing this. Worked as expected in Sierra. Disabling the streamkeys extension brought back the normal behaviour. 

Could also be a Chrome thing but I haven't really been monitoring my version number for that.

**Comment by vladasbarisas** [comment]
I also have the same issue. Looks like Streamkeys takes over the media keys and doesn't ever release them.

**Comment by Drewkan** [comment]
Yeah, this is a really annoying problem. I have to enable / disable everytime i want to hear Spotify

**Comment by Drewkan** [comment]
I just found out that if i press SHIFT + media Key it works outside chrome.

And when pressing only media key it goes to Chrome. I'm okay with that 🥇

**Comment by berrberr** [comment]
Chrome issue
