### ISSUE TITLE
multiple hotkey bindings for specific functions? 

### ISSUE THREAD

**Issue by ndroftheline** [berrberr/streamkeys#406]
hey crew! love streamkeys, thanks so much. 

i'm curious if there's any way to set multiple hotkeys for a function like play/pause? i'm constantly switching machines, keyboards, etc due to my work. i like the play button functoin but lots of keyboards don't have media keys - is there any way that i can set an alternative/second key combination to this functoin without losing the media key functionality on machines where it is present? 

cheers!

**Comment by berrberr** [comment]
Ah, interesting use case. Unfortunately the Chrome commands api only allows one hotkey per command so this is not possible, sorry!
