### ISSUE TITLE
[Feature request] Enable option to only use the most recently visited tab by default

### ISSUE THREAD

**Issue by anka-213** [berrberr/streamkeys#407]
I often have multiple Youtube videos open in multiple tabs. By default, streamkeys pauses/unpauses all open videos at the same time unless you disable some of them in the streamkeys menu.

I  would like to only have an option where only the most recently played media (or recently visited tab) is enabled by default so I won't need to open the menu and disable the other ones manually.

**Comment by anka-213** [comment]
Oops, this already exists. Sorry.

However, it should be the default in my opinion.

**Comment by jeffvandyke** [comment]
Just came to say what a pleasant surprise for me this was. I've had this for about a year, and it was enabled for me automatically without me doing anything (must have been an update or a reinstall), and it's exactly the behavior I wanted. Kudos!
