### ISSUE TITLE
Global Hotkey Setting wont save

### ISSUE THREAD

**Issue by Nikralx** [berrberr/streamkeys#409]
When I toggle the "In Chrome" setting to "Global Hotkey" it appears the setting does not save when I close the Hotkey window. Is this a problem with my chrome or a problem with the extension? They hotkeys work fine. Just won't work outside of chrome anymore.

**Comment by xai1983kbu** [comment]
I was not able to set my shortcut to "global"  here --> chrome://extensions/shortcuts
Then I reinstalled extension and started to use default options which are "global" by default

**Comment by Nikralx** [comment]
Reinstalling seemed to fix it.
