### ISSUE TITLE
amazon prime music not working

### ISSUE THREAD

**Issue by chrishough** [berrberr/streamkeys#413]
Unfortunately amazon prime music is not working or being detected

**Comment by Camron** [comment]
Seems to work fine for me. Are you on amazon.com or an international version?

**Comment by tdenewiler** [comment]
I am using streamkeys (v1.7.8) on Google Chrome browser (Version 72.0.3626.119 (Official Build) (64-bit)) in Linux Mint 18. I am not able to change tracks or play/pause with this extension.

This extension worked on Chromium browser up until this week, but then Amazon Music Unlimited started saying that Chromium is an unsupported browser and that I had to use either Chrome or Firefox. I really like this extension.
