### ISSUE TITLE
Gone from Chrome Web Store?

### ISSUE THREAD

**Issue by smtchahal** [berrberr/streamkeys#416]
https://chrome.google.com/webstore/detail/streamkeys/ekpipjofdicppbepocohdlgenahaneen

What happened?

**Comment by fent** [comment]
Google

**Comment by WeedSnorkeler** [comment]
did they not specify why it got taken down again?

**Comment by smtchahal** [comment]
Apparently it got taken down a year ago, but got added again a day later: #282

**Comment by berrberr** [comment]
Yeah, so Google took this down because of the jquery library apparently. I asked for more info but they didn't really elaborate (as usual with Google support).

We are using a really old jquery version so I'm thinking that that might be the issue. I have a branch to update to the current version and I will try submitting that to the store today.

**Comment by Mattie112** [comment]
Can you upload the packed extension for manual install?

**Comment by smtchahal** [comment]
@Mattie112 I had the extension installed on another laptop before it got pulled so I managed to repackage it. Here:

https://drive.google.com/open?id=1NQU8dWoUogfIPo-BbMfElTb78S0XL99S

**Comment by berrberr** [comment]
Here is a link to zipped extension: https://drive.google.com/file/d/1T4VdEpbUzZO_FNe7OCOEO1Ac8SEZceBn/view?usp=sharing

You can use load unpacked extension button on `chrome://extensions` page in developer mode to add. Also CRX from @smtchahal should work, I have not tested it though.

The latest version got rejected again ... and again no info from Google after asking 🤦‍♂️ . I read somewhere that they might have an issue with minified files now (all the extension files are uglified) so I'm going to try again with a version with no minified files.

**Comment by jgritten** [comment]
Loading the unpacked extension worked great. Thank you!

**Comment by Wargazm** [comment]
Hi,
It seems the extension is still gone from the Chrome store.  Any progress?  Any response from Google?

Thanks

**Comment by isaaclw** [comment]
Could you add a link to your page about how to download the extension? Then it'll be easier for noobs to find the plugin.

**Comment by berrberr** [comment]
I completely removed jquery from the extension code and resubmitted. Google kept complaining about the jquery library file, so hopefully this will fix it. No idea why though, I am sure that 1000s of extensions use jquery currently :S

If this doesn't work then I'm out of ideas for the time being

**Comment by IanKemp** [comment]
@berrberr Any updates? Is there any way we can put pressure on Google to actually be useful? There are other global hotkeys extensions on the Chrome store but I really like this one...

**Comment by dittoslash** [comment]
You can (at least temporarily) re-enable it from the chrome://extensions page. Not sure if that'll last, but it works for now.

**Comment by Wargazm** [comment]
Is it possible to download the source and install the extension manually?  I've never done anything like that, I'd appreciate any help.

**Comment by bityob** [comment]
@Wargazm 

Yes, you can use the source code, and install it like this.

1. Download the source code from here (provided by @berrberr)

https://drive.google.com/file/d/1T4VdEpbUzZO_FNe7OCOEO1Ac8SEZceBn/view?usp=sharing

2. Extract the files to a folder, where you want to keep it

3. Go to chrome://extensions/ in a new tab

4. Enable developer mode (right corner)

![image](https://user-images.githubusercontent.com/20026896/39588395-60c71404-4f04-11e8-9c21-7ebb37c61df2.png)

5. Press "Load Unpacked" and browse to the folder below

![image](https://user-images.githubusercontent.com/20026896/39588997-a62066c6-4f05-11e8-99d4-7a92ed141702.png)

6. Press Ok, and you done

![image](https://user-images.githubusercontent.com/20026896/39589024-b9586630-4f05-11e8-9da3-2b825a1b7ce2.png)

**Comment by Wargazm** [comment]
Thanks, worked great!

**Comment by mehdichaouch** [comment]
@berrberr what you don't use https://github.com/berrberr/streamkeys/releases to upload your ```.crx``` release ?

**Comment by giogziro95** [comment]
That whole attitude from Google Support strangely reminds of [what happened to Streamus](https://thenextweb.com/insider/2015/07/21/how-youtube-killed-an-extension-with-300000-users/)...

**Comment by TristanP13** [comment]
It would appear to be back! Looks like whatever berrberr did went and resolved it. I'm really glad because Chrome pesters you whenever you open it to disable Developer Mode for your 'safety'.

**Comment by cxw42** [comment]
Many thanks, @berrberr!

**Comment by gawdn** [comment]
Hey, it's great that extension is back on the Chrome store! However even after a full extension reinstall (through the official chrome store) the extension is still flagged as "violates the Chrome Web Store policy". This is fine but it keeps switching it off every time Chrome is restarted (frustrating!). Is there anything I could do about that?

![image](https://user-images.githubusercontent.com/26182503/39861883-63652684-5485-11e8-882d-b33143ed4ab0.png)

**Comment by imekachi** [comment]
It works now!!
I simply removed the extension and re-install it from chrome webstore.

![image](https://user-images.githubusercontent.com/5445243/40215520-331890ea-5a8b-11e8-9362-549354e3da71.png)

Thank you gus 👍

**Comment by giogziro95** [comment]
Unfortunately, reinstalling extension will reset the settings... Any plans on adding a backup and restore functionality? There is a way to manually do that via the Developer Tools, but that's not very user-friendly.

**Comment by Wargazm** [comment]
I'm seeing the same behavior as gawdn....every time chrome restarts Streamkeys is disabled by Chrome and I have to manually re-enable it.  Definitely irritating.  Any advice from anyone seeing the same behavior?

**Comment by StalePhish** [comment]
Mine isn't disabling every time I re-open Chrome, but it is the second time I've had to re-enable it within a week or so

**Comment by Xalaxis** [comment]
Mine's just started doing it again after stopping for about a week.

**Comment by m1lhaus** [comment]
I have to confirm the issue still persist. I even tried remove Chrome, delete all Chrome folders from AppData and started from scratch. It didn't help.

**Comment by evenlis** [comment]
This is all very tedious. I've [added a post](https://productforums.google.com/forum/#!topic/chrome/-YMnEGTXQmA;context-place=forum/chrome) on the google chrome help forum voicing my frustration.

**Comment by psifertex** [comment]
Looks like it might be resolved? I had to manually re-enable it yet-again but it looks like from the chrome plugin page it's not being blocked anymore?

**Comment by dcormier** [comment]
Correct, @psifertex. It seems to be resolved. It's available on the Chrome web store again. But if it was disabled already it might still show that it violates the store policies. I reenabled and refreshed and that message went away.

**Comment by m1lhaus** [comment]
Still the same behavior. Warning message is shown and Chrome disables this extensions kind of randomly (on restart? not sure). I've tried remove/add extension again from webstore but after I click "Check for updates" button in extension manager, StreamKeys is blocked immediately with same error message. Really annoying. Any news from Google support?

**Comment by quisse** [comment]
A guy at google says the following if the issue persists: 
https://productforums.google.com/d/msg/chrome/-YMnEGTXQmA/axd-pXuNAAAJ

> Do you only have this issue? Try to do a hard reset of your Google Chrome web browser.
> Follow the steps here below to uninstall Google Chrome:
> 1. Go to your software list, and uninstall Google Chrome from the list
> http://windows.microsoft.com/en-us/windows/uninstall-change-program#uninstall-change-program=windows-7
> 2. Go to this location:
> C:\Users\YOUNAME\AppData\Local\Google\
> C:\Program Files (x86)\Google\
> 3. And delete that "Chrome" folder (for both location, if there is a Chrome folder)
> 4. Restart your computer
> 5. Install Google Chrome from www.google.com/chrome

**Comment by m1lhaus** [comment]
I've already answered to Google Groups thread, but just a quick sit rep, this didn't help.

**Comment by m1lhaus** [comment]
Anybody still experience this issue? For me it's gone, finally. It just disappeared in past days on both of my computers.

**Comment by m1lhaus** [comment]
Of course the issue is gone, not the plugin :-)

**Comment by psifertex** [comment]
Yeah, there's another thread with more discussion and I believe it's resolved now and should be closed.
