### ISSUE TITLE
Global Hotkeys don't seem to be firing any events.

### ISSUE THREAD

**Issue by Jakob-Maudience** [berrberr/streamkeys#420]
Streamkeys seems to be ignoring all of my hotkeys. I've tried the default media keys, and I've tried setting custom hotkeys but none of the events seem to be firing from the keyboard (I've tried YouTube and Soundcloud). The buttons on the extension popup still work though. 

I'm using the 1.7.3 unpackaged version downloaded from this link -[https://github.com/berrberr/streamkeys/issues/416#issuecomment-380672758](url)
Chrome Version 65.0.3325.181

**Comment by CollinErickson** [comment]
I had this same problem, but it went away after restarting Chrome.

**Comment by Jakob-Maudience** [comment]
It turns out this solved the issue for me as well when I set custom hotkeys (it still doesn't seem to recognise my media keys). Closing the issue.
