### ISSUE TITLE
[Suggestion] Control the first tab

### ISSUE THREAD

**Issue by HerelAdrastel** [berrberr/streamkeys#421]
Hi,

It would be great to add an option to control only the first player tab. Because now, when I click on Play on my keyboard, all my YouTube tabs play/pause.

Thank you ^^

**Comment by pedromartinez11** [comment]
Sounds like this setting does what you're suggesting:
![screen shot 2018-05-03 at 1 41 54 pm](https://user-images.githubusercontent.com/699998/39601742-da62cf10-4ed7-11e8-8ad0-bfffa3789dc7.png)

**Comment by HerelAdrastel** [comment]
Woops, sorry, I haven't thought to use this option. Thanks a lot ;)
