### ISSUE TITLE
YouTube videos can still be played even when the player is not visible

### ISSUE THREAD

**Issue by ElderEphemera** [berrberr/streamkeys#430]
If you press back when watching a YouTube video to go back to the YouTube homepage, the video player is still on the page even though it's not visible. Streamkeys can still interact with this hidden video.

**Comment by WhistlePayer** [comment]
If it's useful: I looked at the page source and there's a "ytd-watch" tag that contains the video player and this tag has the "hidden" attribute when the player isn't visible.
