### ISSUE TITLE
YouTube Music support

### ISSUE THREAD

**Issue by rock3r** [berrberr/streamkeys#434]
https://music.youtube.com is available to the public, would be very nice to get support for it.

**Comment by siriusnottin** [comment]
I agree, Youtube Music support would be great! 🙂

**Comment by lleites** [comment]
Its already merged #431 
So it should be available on the next release!

**Comment by Redominus** [comment]
IS there an ETA?

**Comment by AllenKOO** [comment]
I can't wait any longer for this function~~~

**Comment by berrberr** [comment]
This has been added
