### ISSUE TITLE
 Send commands to most recently focussed tab

### ISSUE THREAD

**Issue by VarunAgw** [berrberr/streamkeys#444]
I would rather like to have this feature. I feel it's way more useful.

Suppose I am currently on pandora tab. Now media key will play/pause it no matter when I started it (because it's the latest on focus).

Similarily if I give to give a tab temorary priority, I will just switch to it once, and then keep doing my work. In current solution, I have to close it, and start it again to make it most recent.

**Comment by duranivan** [comment]
Yes please, this feature is much better than the current one `send command to most recent tab only`, as it can dynamically change the player I want to send commands to by just focusing on the tab.

**Comment by nemchik** [comment]
Rather than close the tab you could simply pause and then play.

I do think the idea of having an option to give priority to the tab in focus might make sense.
