### ISSUE TITLE
Autohotkey not working

### ISSUE THREAD

**Issue by skibbipl** [berrberr/streamkeys#447]
Hi,
I had to replace my keyboard with media files to another one without media keys. So I decided to map some shortcuts with Autohotkey. My script works well for Spotify, but streamkeys are not responding to them. Do I miss something in streamkeys configuration?

**Comment by VarunAgw** [comment]
I am able to use AHK with StreamKeys. Basically I send {Media_Play_Pause} to chrome and StreamKeys capture it.
Have you assigned hotkey properly in extension page. Is it Global or Chrome only?

**Comment by Merurino** [comment]
So, I have a laptop with the physical media key, but I use another keyboard that doesn't have it.
I set up the {Media_Play_Pause} in AHK and it works fine for example with the spotify app.

I was trying it with streamkeys and I couldn't get it to work. Even if I try spotify's website for example the AHK shortcut doesn't work, while the physical key in the laptop keyboard works fine.
