### ISSUE TITLE
Doesn't work with the new deezer website

### ISSUE THREAD

**Issue by robert1826** [berrberr/streamkeys#452]
the extension was working very good until the deezer team has pushed out a new website design prompting users to switch to the new design ... when I click ok I found out that the extension doesn't work properly (i.e. doesn't pause or play next when hitting the appropriate keys) however it detects that deezer is open.

**Comment by garlix** [comment]
I've updated the CSS selectors in order to work with the new Deezer website.
Check #454

**Comment by garlix** [comment]
Quick&Dirty fix waiting that @berrberr approves my modifications:

1. Go to your chrome extensions page
1. Enable the developer mode (upper right corner)
1. Copy Stramkeys ID
1. Go to `%LOCALAPPDATA%\Google\Chrome\User Data\Default\Extensions\<your-streamkeys-id>\<streamkeys-version>\js\controllers`
1. Edit `DeezerController.js` replace `new b({siteName:"Deezer" ... })}()},{BaseController:2}]` with

`new b({siteName:"Deezer",buttonSwitch:true,pause:".player-controls button[aria-label=Pause]",play:".player-controls button[aria-label=Play]",playNext:".player-controls button[aria-label=Next]",playPrev:".player-controls button[aria-label=Back]",playState:".player-controls button[aria-label=Pause]",song:"a.track-link:nth-of-type(1)",artist:"a.track-link:nth-of-type(2)"})}()},{BaseController:2}]`

Good listening

**Comment by berrberr** [comment]
Thanks @garlix! This is fixed in 1.7.7 which should be updated automatically.

**Comment by delmicio** [comment]
@robert1826 is it working for you? I've re-activated Streamkeys but is not working on Deezer at all.
@garlix @berrberr

**Comment by robert1826** [comment]
@delmicio it's working for me

**Comment by dimsanchuk** [comment]
It does not work for any localization, except english.

**Comment by garlix** [comment]
@dimsanchuk try to change locally your streamkeys plugin (follow [this steps](https://github.com/berrberr/streamkeys/issues/452?_pjax=%23js-repo-pjax-container#issuecomment-425364098) ) with this:

`new b({siteName:"Deezer",playPause:"div.player-controls > ul > li:nth-child(3) > button",playNext:"div.player-controls > ul > li:nth-child(5) > div > button",playPrev:"div.player-controls > ul > li:nth-child(1) > div > button",playState:"svg.svg-icon-pause",song:"a.track-link:nth-of-type(1)",artist:"a.track-link:nth-of-type(2)"})}()},{BaseController:2}]`

If it works I'll update it

**Comment by dimsanchuk** [comment]
@garlix yes, it works. Thanks!

**Comment by garlix** [comment]
Opened pull request #458 . Added also mute button

**Comment by delmicio** [comment]
@garlix is that PR a fix for everyone? any localization? I'm using Spanish Deezer

**Comment by garlix** [comment]
Yes, it should totally work with every localisation. But until @berrberr doesn't accept my pull request, the Chrome store version will work only for the English language. In the meanwhile, you can modify your local version following my previous comment:
https://github.com/berrberr/streamkeys/issues/452#issuecomment-426214630
