### ISSUE TITLE
[feature] Add more information to "Send notification of player(s) state" command output

### ISSUE THREAD

**Issue by norcalli** [berrberr/streamkeys#455]
I would like to parse the notifications from the player state to display information in a status bar, and would like it if as much information as possible could be present such as:

- isLiked: if available, the status of the like toggle
- isPlaying
- literally everything, like current song position, volume levels, anything that's available that shows the current state.

I can try to take a look at implementing this later, but would appreciate assistance to help me do it faster.

**Comment by bsinky** [comment]
I'm not sure exactly why I went with 2 information lines for notifications originally, it seems like there's nothing preventing us from having more and including the information you mention.

I did a quick test just to confirm the Chrome Notifications API would allow more than 2 items, like [the documentation says it will](https://developer.chrome.com/apps/notifications#type-TemplateType) (for the `list` type we're using):

![image](https://user-images.githubusercontent.com/5004786/46534498-f0b22f80-c86d-11e8-9d6c-bba7c273cfde.png)

The extra 2 lines I added appeared just fine, so I guess it works.

Streamkeys doesn't currently scrap song position from any of the sites it supports. I had done a little experimenting with adding that in the past, pulling it as percentage based and using that with Chrome's `progress` Notification. It's definitely possible, but it'd be better to take a simpler approach and just pull current time and total time in a "0:00" format, and display that, which is probably what you were thinking. The `progress` notification, while kind of cool, just doesn't allow you to show much other information in the notification popup.

One last thing, I've thought it would be cool to add buttons to the notifications, `isPlaying` would be perfect for that as it could be a clickable play/pause button. A "skip/next" button would be useful too, IMO. I haven't tested out buttons in the Notification API yet but the docs say they're supported (up to 2 buttons for `list` type Notifications).
