### ISSUE TITLE
Keyboard media controls don't work on macOS Mojave

### ISSUE THREAD

**Issue by jefferjacobs** [berrberr/streamkeys#463]
Apple just release macOS Mojave recently, and after I updated, the keyboard media controls are no longer working with Streamkeys like they were previous to this update. It seemingly ignores the extension completely.

**Comment by montecruiseto** [comment]
Yep, my beloved streamkeys stopped working as soon as I upgraded to Mojave.
Any fix?

**Comment by ahildoer** [comment]
+1

**Comment by Biert85** [comment]
I had the same problem, fixed it by allowing Chrome to access accessibility features via _System preferences > Security & Privacy > Accessibility_ and restarting Chrome.

**Comment by ahildoer** [comment]
Tried the Accessibility option but no love. See screen shot. Approved Google Chrome for Accessibility access. Quit (actual quit not just close windows) both Chrome and iTunes. Opened Chrome, went to pandora.com, pressed play/pause and iTunes launched. 

![streamkeys_and_mojave](https://user-images.githubusercontent.com/438567/48371998-7e0d4e80-e67a-11e8-9375-3bcf26e008e5.png)

**Comment by junaidnasir** [comment]
@ahildoer install [Play music extension](https://chrome.google.com/webstore/detail/google-play-music/fahmaaghhglfmonjliepjlchgpgfmobi) chrome will now capture global media keys which is then passed to streamkeys

**Comment by dwiel** [comment]
restarting chrome after installing the plug-in fixed the issue for me
