### ISSUE TITLE
Edge browser support

### ISSUE THREAD

**Issue by nemchik** [berrberr/streamkeys#468]
I'm wondering if it would be possible to support Edge?
https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions This may be useful. I tried it myself and I have the extension icon and popup working to show "No music sites open." but when I actually open a music site it removes that text and does not show anything. The blue buttons (options, help, donate) are always visible regardless if a music site is open or not. The popup itself seems to be a bit small and I have to scroll up and down inside of it.

**Comment by mkarpoff** [comment]
So I've started digging into this because I want it too. I've run into an issue where two API call for chrome (commands.onCommand, commands.getAll) needs a edge equivalent replacement. Still digging the rest seams to work really smoothly

**Comment by mkarpoff** [comment]
So after some digging if you look [`at the documents`](https://docs.microsoft.com/en-us/microsoft-edge/extensions/api-support/extension-api-roadmap) you'll see that the commands API is "Under consideration". So you can't actually register the key mappings necessary for this to work. Looks like we need to wait for the API for an easy conversion using this tool or have someone more knowledgeable than I try to tackle this problem.

**Comment by nemchik** [comment]
Recent news indicates Edge will be switching to the Chromium engine. I wonder if that will affect the availability of key inputs.

**Comment by mkarpoff** [comment]
It looks like the rendering engine is what they are taking from chromium if that's the case would that effect the browser APIs? I'm unsure I usually do system dev.

**Comment by mkarpoff** [comment]
I'll keep an eye on this with insider builds

**Comment by nemchik** [comment]
Since edge is very switching to chromium with full support for chrome extensions this is no longer an issue. I've already tested streamkeys in edge canary and dev builds and it's worked flawless.
