### ISSUE TITLE
Media keys doesn't work for windows apps  when the  extension in enabled 

### ISSUE THREAD

**Issue by RichardsRobinR** [berrberr/streamkeys#470]
when the extension is disabled , for groove music app i.e windows standard media key function is working properly but when the extension is enabled ,it works for the websites at the same time it doesn't work for any windows app.

**Comment by cubimon** [comment]
Did you try to change the scope from "global" to "in chrome" in the hotkey settings?

![image](https://user-images.githubusercontent.com/3812715/50117611-c73e5880-024d-11e9-8357-fe7a1b7e582b.png)

If this isn't sufficient, there must be some way to tell chrome that a command was processed or ignored. But I couldn't find anything in the [chrome documentation](https://developer.chrome.com/extensions/commands).
