### ISSUE TITLE
Not working on new BBC Sounds radio sites

### ISSUE THREAD

**Issue by bobf32** [berrberr/streamkeys#479]
E.g. https://www.bbc.co.uk/sounds/play/live:bbc_6music

**Comment by bobf32** [comment]
Don't understand.

**Comment by cubimon** [comment]
I couldn't find a like/dislike functionality/a button that looks like this 👍/👎. But the [current code](https://github.com/berrberr/streamkeys/blob/master/code/js/controllers/BBCRadioController.js#L11) contains selectors to like/dislike audio. The new play/pause selector would be `#p_audioui_playpause_circle`, the mute selector `.p_audioIcon`, the song selector `.gel-trafalgar` (not 100% sure about this). Artist stays the same, but I couldn't find a like/dislike button.

**Comment by cubimon** [comment]
this stuff sometimes appears in an iframe (selector is `#smphtml5iframesmp-wrapper` or simply `iframe`) and the next moment there is no iframe ¯\\\_(ツ)\_/¯, probably requires some kind of detection of the iframe?
