### ISSUE TITLE
Adding change playback rate?

### ISSUE THREAD

**Issue by maranqz** [berrberr/streamkeys#482]
Hello.
What do you think about adding [playbackRate](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/playbackRate) on '+', '-' button on keyboard and input field for set determinate value.

The hidden media element catching by 
```js
var createElement = document.createElement;
document.createElement = function(tagName, options){
   let newElement = createElement.call(document, tagName, options);;
   if(tagName == 'audio'){
    /// changing playbackRate by button
    }
    return newElement 
}
```

**Comment by cubimon** [comment]
this could be also integrated in [mpris](https://specifications.freedesktop.org/mpris-spec/latest/Player_Interface.html) as Rate. I like this solution to find audio/video elements, but some websites create audio/video elements in html and I am pretty sure that the browser doesn't call js functions when parsing html. And there is also soundcloud, which creates more than one audio element for a single song.

**Comment by maranqz** [comment]
I think can add play, end, pause event listener for changing playbackRate by playing media.

If audio/video elements creating in html, i can find them and do same.

Do you have an ideas for other problems?

**Comment by cubimon** [comment]
I would expect the `playbackRate` to stay constant if a audio/video element is paused/resumed. But surely if that is not the case you could, as you said, use listeners to overwrite the `playbackRate`. The soundcloud problem I described above probably won't be a problem, as you could set the `playbackRate` for all elements. Multiple audio elements is only a problem for seeking, which isn't discussed here in this issue. Btw the embedded controller also relies on audio/video elements.
