### ISSUE TITLE
No Working for Player.fm

### ISSUE THREAD

**Issue by brentdavis75** [berrberr/streamkeys#485]
Hi,

This extension doesn't seem to be working for Player.fm.

Any ideas from anyone?

Thanks

**Comment by cubimon** [comment]
`.play-prompt`, or alternatively `.fa-pause` and `.fa-play` for play/pause.
Next song `.fa-fast-forward`, previous song `.fa-fast-backward`, but I couldn't find a song list that had these buttons enabled:
![image](https://user-images.githubusercontent.com/3812715/51691677-862f2600-1ffb-11e9-9594-f83bdb276485.png)
