### ISSUE TITLE
Plex stopped working.

### ISSUE THREAD

**Issue by lailoken** [berrberr/streamkeys#490]
Seems like the new updated of Plex stopped it from working (again).

I've tried to debug it in Chrome, and it recognizes the song playing correctly, but clicking on the pause play buttons in the extension popup only results in a Console error:

```
PlexController.js:1 STREAMKEYS-ERROR: Element not found for mousedown. i[class^=plex-icon-player-next-]
b.exports @ PlexController.js:1
d.hasOwnProperty.c.(anonymous function) @ PlexController.js:1
click @ PlexController.js:1
c.playNext @ PlexController.js:1
c.doRequest @ PlexController.js:1
EventImpl.dispatchToListener @ VM73032 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM73038 extensions::utils:138
EventImpl.dispatch_ @ VM73032 extensions::event_bindings:387
EventImpl.dispatch @ VM73032 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM73038 extensions::utils:138
messageListener @ VM73039 extensions::messaging:240
EventImpl.dispatchToListener @ VM73032 extensions::event_bindings:403
publicClassPrototype.(anonymous function) @ VM73038 extensions::utils:138
EventImpl.dispatch_ @ VM73032 extensions::event_bindings:387
EventImpl.dispatch @ VM73032 extensions::event_bindings:409
publicClassPrototype.(anonymous function) @ VM73038 extensions::utils:138
dispatchOnMessage @ VM73039 extensions::messaging:392
PlexController.js:1 STREAMKEYS-ERROR: Element not found for mouseup. i[class^=plex-icon-player-next-]
```

I've updated the Plex Web Player to version:
Version 3.85.2

(The keystrokes are working (Google Play Music, etc. still works).)

Not sure what changed. Focus is not the issue and all my aliases are correct.

**Comment by lailoken** [comment]
Thanks @timdorr , It would really be cool of StreamKeys had a 'custom' site where I would have been able to just paste the relevant JS functions to test with (copied from the Plex plugin in the repository for instance).

I hacked the extension in the UserData to try a few things, but it was cumbersome and I was not able to get it to work regardless... it was fun trying, but my web coding ability is not my strongest suit.

**Comment by lailoken** [comment]
I've checked out the project and built it locally. I've applied the change (which I notice was the same non-class-based selection as originally used) and can confirm it is working for me locally.

**Comment by stanstrup** [comment]
Could you share this build? It doesn't seem like a new official build is forthcoming.

**Comment by cubimon** [comment]
@stanstrup https://github.com/berrberr/streamkeys/pull/492#issuecomment-464082385

**Comment by stanstrup** [comment]
Thanks! Works. Sanity restored.

**Comment by vidmaster2000** [comment]
Is there an ETA as to when the fix is going to be integrated into the main extension?  I really enjoy being able to control Plex while I'm working in other applications.
