### ISSUE TITLE
Does Not Work on MacOS Mojave

### ISSUE THREAD

**Issue by paulrrogers** [berrberr/streamkeys#493]
At least not with Youtube, even when browser tab has focus. Only works when widget buttons pressed

**Comment by cubimon** [comment]
Did you try different hotkeys than media keys to pause/play?

**Comment by romashko** [comment]
Doesn't work for me either. Other shortcuts work fine, but not the media keys.

**Comment by romashko** [comment]
It is probably Chrome issue, it does not detect media keys as extension shortcuts even with accessibility access enabled

**Comment by ZachSaucier** [comment]
I'm facing the same issue with Windows 10. Tried multiple keyboard shortcuts, including some that other extensions can successfully use.

**Comment by lailoken** [comment]
It is also possibly iTunes grabbing those. Apple is pretty stingy with that access... there are some apps out there which may help to liberate those.
ie. https://www.gearmusicplayer.com/extras.html
