### ISSUE TITLE
Seems like plex stopped working again

### ISSUE THREAD

**Issue by endlessloop1** [berrberr/streamkeys#506]
I tried at plex.tv and at my alias which was working before.  It shows plex when I click the extension, but the buttons in the extension or my keyboard don't do anything now.  Works on all other sites I've tested.  Plex version 3.95.2

**Comment by davidjaca94** [comment]
The same thing has happened to me for a while, I suppose it will be for some plex updating

**Comment by stanstrup** [comment]
There is already a fix but it seems not on the official page yet https://github.com/berrberr/streamkeys/pull/492#issuecomment-464082385

**Comment by davidjaca94** [comment]
Still not working...
