### ISSUE TITLE
Add support for Google Podcasts

### ISSUE THREAD

**Issue by SUPERCILEX** [berrberr/streamkeys#513]
Here's a sample link: https://podcasts.google.com/?feed=aHR0cDovL2ZlZWRzLnN0b3ducG9kY2FzdC5vcmcvc3Rvd25wb2RjYXN0&ep=5&at=1558317672198

**Comment by jayminghnog** [comment]
I totally agree!

**Comment by EmperorEarth** [comment]
@SUPERCILEX, @jayminghnog 

@nemchik merged in a fix
Google Podcasts should be supported in the next release
