### ISSUE TITLE
Unpacked version for Chrome

### ISSUE THREAD

**Issue by liquidmetalrob** [berrberr/streamkeys#516]
In the readme it says "In Chrome, load the unpacked extension from build/unpacked-dev/".
Where is "build/unpacked-dev/"?

**Comment by cubimon** [comment]
run `npm run develop` to create the `build` folder

**Comment by liquidmetalrob** [comment]
Thanks for the help. Unfortunately that's not working for me. I get this error:

Running "jshint:all" (jshint) task

code/js/controllers/CastboxController.js
  line 1  col 1  Unnecessary semicolon.

1 problem

Warning: Task "jshint:all" failed. Use --force to continue.

Am I doing something wrong?

**Comment by liquidmetalrob** [comment]
OK, I've managed to get it working by loading up CastboxController.js, comparing it to the other controllers and getting rid of a line break after the first semicolon. Although it's still strange that that error hasn't been fixed in the files.
