### ISSUE TITLE
[BUG] Working randomly in ubuntu

### ISSUE THREAD

**Issue by maxjf1** [berrberr/streamkeys#517]
The plugin randomly work with ubuntu. 

When not working, ubuntu shows the block warning, that means no player found to play/pause (screenshot)

When i disable and enable the plugin again (and reload the player page) it starts working again...

![image](https://user-images.githubusercontent.com/6114888/58331412-7e4b8b00-7e0f-11e9-9848-91fd64ad213f.png)

## How to reproduce it:
(using an ubuntu with chrome and the extension already installed)

1. Open chorme and open some player such as spotify
2. use the keyboard play/pause button (ubuntu will show the block icon, meaning that there is no player to use it)
3. right click the extension icon > manage extension
4. disable and re-enable the extension
5. refresh the player page and try to use the keyboard play/pause again (it will work)

if you close and open chrome again, the problem returns :cry:

**Comment by cubimon** [comment]
Did you try to bind different keys? If I am not mistaken some operating systems block media keys. Does the popup work?

**Comment by maxjf1** [comment]
no, i am using the keyboard media keys. But this is not the problem.

the plugin will work if i disable and re-enable it, but not if i just open chrome and try to use it.

the popup works.

**Comment by maxjf1** [comment]
After updating to Ubuntu 18.10, the bug seems to be solved. I will test it for a few days and check.

**Comment by maxjf1** [comment]
Working as expected on ubuntu 18.10 and 19
