### ISSUE TITLE
Problem with SK on Udemy site

### ISSUE THREAD

**Issue by betfix** [berrberr/streamkeys#518]
I have a problem using SK on Udemy. Some time ago (a month or two maybe) it worked. But recently Udemy updated their UI, they added new features and also changed the player a bit. 

After clicking on SK icon in Chrome it recognizes that Udemy is open and below displays a few buttons. Clicking on the "play/pause" button doesn't do anything. Also, I have hotkey "Alt+Space" configured to play/pause videos and pressing this hotkey also doesn't do anything.

For comparison, e.g. on YouTube, both methods work fine.

**Comment by xelaos** [comment]
;(function() {
  "use strict";

  var BaseController = require("BaseController");

  new BaseController({
    siteName: "Udemy",
    playPause: "[data-purpose=play-button]",
    play: "[data-purpose=play-button]",
    pause: "[data-purpose=pause-button]",
    playNext: "[data-purpose=go-to-next]",
    playPrev: "[data-purpose=go-to-previous]",
    mute: ".vjs-volume-menu-button",
    playState: ".vjs-playing",
    buttonSwitch: true
  });
})();
Just clone the repository as explained in the readme and change the UdemyController.js to: 
`;(function() {
  "use strict";

  var BaseController = require("BaseController");

  new BaseController({
    siteName: "Udemy",
    playPause: "[data-purpose=play-button]",
    play: "[data-purpose=play-button]",
    pause: "[data-purpose=pause-button]",
    playNext: "[data-purpose=go-to-next]",
    playPrev: "[data-purpose=go-to-previous]",
    mute: ".vjs-volume-menu-button",
    playState: ".vjs-playing",
    buttonSwitch: true
  });
})();
`

**Comment by betfix** [comment]
Here is what I did for a quick(?) fix without rebuilding the project:

- Pressed the key and nothing happened
- Opened console and searched for error: 
STREAMKEYS-ERROR: Element not found for click. .vjs-play-control
b.exports @ UdemyController.js:1
c.click @ UdemyController.js:1
c.playPause @ UdemyController.js:1
c.doRequest @ UdemyController.js:1

- Opened the javascript file by clicking above link for line at c.click
- Pretty print minified file
- Set breakpoint at that line
- Pressed key again to reach the breakpoint
- In Scope/Local panel, changed:
this.selectors.play property to "[data-purpose=play-button]" (was ".vjs-play-control")
this.selectors.pause property to "[data-purpose=pause-button]" (was ".vjs-play-control")
- Resume and delete breakpoint

Now the key seems to work for subsequent videos as long as the page is not reloaded.
