### ISSUE TITLE
Not working in brain.fm

### ISSUE THREAD

**Issue by mitze** [berrberr/streamkeys#523]
Some weeks ago it stopped working the play/pause functionality.

It is possible that the problem was caused by a name change in the class of the play button.

In _BrainFMController.js_ the name is **".modules-music-player-css-PlayControl__wrapper___2ROhW"** and in the actual page is **".PlayControl__wrapper___341vD"**

Thanks.

**Comment by mitze** [comment]
#525

**Comment by archk19** [comment]
Still not working for me.
