### ISSUE TITLE
Streamkeys Don't work sometime

### ISSUE THREAD

**Issue by movibeast** [berrberr/streamkeys#526]
Hi, Streamkeys Don't work sometime. I checked if my keys are correct or not and yea those was correct. 
Streatkeys is not working for me all the time, sometime it works and sometime it doesn't.
Anyone know why is it??

It is happening to me from a long time (around 5-6 months) but I never had time to contact.

Please let me and if there is something please fix it.

Thanks
StreamKeys Supporter

**Comment by movibeast** [comment]
😭😭😭 anyone?

**Comment by cubimon** [comment]
I don't have these issues. We probably need some instructions/more info to replicate this behaviour.

**Comment by cubimon** [comment]
And even if we fixed it, it also depends on @berrberr who is pretty inactive to accept changes
