### ISSUE TITLE
State of maintenance

### ISSUE THREAD

**Issue by nemchik** [berrberr/streamkeys#530]
So I've just closed #527 after looking at some of the other PRs open in the repo.

- #505 : I feel like this is probably the highest priority issue to be addressed. This new version has already been released yet the PR is not merged to the master branch. There have been PRs made and merged AFTER this PR, so we're going to get to a point of having merge conflicts. I don't think we're there yet, but I feel this should be a high priority to resolve to prevent that scenario.
- #528 : I feel like this should take second priority (top priority being preventing merge conflicts) so that we can see whether builds for future PRs pass or need additional work or tweaks. Also FYI GitHub Actions will be GA in mid November and it may be beneficial to consider using it over Travis-CI since Travis has notoriously always been behind on supporting new versions of OS and dependencies. I've already got some experience adjusting another repo of mine to use GitHub Actions and will gladly assist with this project transitioning to it if that is something @berrberr wants. That can be addressed in a separate issue.
- #476 : This PR is a tremendous effort from @cubimon and @alextsits and I'm thrilled to see it. In some ways it overlaps with #528 which I started without realizing that this PR already existed. I fully understand getting carried away with changes in a PR (see my history on this repo alone!) and I think if the first two issues I mentioned are addressed in order that maybe the additional dependency updates in this PR (npm, lodash, etc) should be split into a new PR and considered before the additional items in this PR (seek/volume + MPRIS, etc).

@berrberr please consider this plan of action and if there is anything I can do to help, or any other contributor you feel could be of assistance with maintaining the project please let us know. We love this extension and want to help!

**Comment by alextsits** [comment]
The above plan seems good to me too, and I am willing to help in any way :)
