### ISSUE TITLE
Twitch no longer working

### ISSUE THREAD

**Issue by at-ng** [berrberr/streamkeys#534]
It seems this add-on no longer works with Twitch after the redesign they did recently. 

> TwitchController.js:1 STREAMKEYS-ERROR: Element not found for click. .qa-pause-play-button

This selector will find the current button "button[data-a-target='player-play-pause-button']".

**Comment by at-ng** [comment]
They might have changed back or they could be experimenting because today it started working again for me.

**Comment by TheBSGamer** [comment]
I'm having this problem too right now. It's been an issue since the redesign and I've been unable to resolve the problem.

**Comment by HLK65** [comment]
I've created a hotfix using Tampermonkey to use until the pr is merged and the extension updated: https://github.com/HLK65/TwitchRedesignStreamkeysHotfix/blob/master/script.js

**Comment by HLK65** [comment]
updated the script to work when page is loading slowly and to apply the fix whenever the url changes

**Comment by K1mac** [comment]
THANK YOU THANK YOU THANK YOU @HLK65 you're a lifesaver.
