### ISSUE TITLE
Double pausing on Youtube

### ISSUE THREAD

**Issue by itsalic** [berrberr/streamkeys#542]
For about a week StreamKeys has started unpausing instantly when I use a hotkey to pause a video. This occurs on both mouse and keyboard hotkeys and the console log looks as follows:

STREAMKEYS-INFO: playPause YoutubeController.js:1
STREAMKEYS-INFO: Player state change YoutubeController.js:1
STREAMKEYS-INFO: Player state change YoutubeController.js:1

So when I press the pause button, it will pause for a split second and then unpause. I've checked my extensions and there should not be any conflicting extensions which would unpause it. Maybe there is something that has changed in a recent update?

Thanks

**Comment by nemchik** [comment]
Chrome now natively supports media keys to control many common sites like youtube and spotify. Try disabling streamkeys and reload the tab you have youtube in and see if your media keys work on youtube. If yes you can re-enable streamkeys and disable the youtube controller from settings. The main thing you'll be missing is the player controls from the streamkeys extension popup.

Please let us know the results.

**Comment by Timums** [comment]
Hello I have the exact same problem, if I pause the video while in the tab with the youtube video it works fine ,but when I am not in that tab it only pauses for half a second ,if I press the pause button again in that split second it pauses like always ,but if I miss that moment the video goes on. I also tried disabling the media keys in chrome ,but that didn´t help either.I hope this helps solve the problem.

**Comment by camdecoster** [comment]
This is happening to me as well. I disabled the hardware media keys flag in Chrome and the issue is still present.

**Comment by camdecoster** [comment]
It turns out that the issue is related to a different extension, [YouTube NonStop](https://chrome.google.com/webstore/detail/youtube-nonstop/nlkaejimjacpillmajjnopmpbkbnocid?hl=en). I think that this issue can be closed.

**Comment by nemchik** [comment]
Anyone else who had the issue able to confirm by disabling ALL extensions in chrome except streamkeys and see how it works?

**Comment by itsalic** [comment]
Correct it was  a conflict with the extension YouTube NonStop which just started happening.
