### ISSUE TITLE
Support for re-asigning media buttons to other keys

### ISSUE THREAD

**Issue by laundmo** [berrberr/streamkeys#544]
It would be awsome if we could map the media keys -> other keys ourselfs (for specific domains or globally).

this would allow for configuring unsupported services and adding additional controls to existing services.

what im thinking of: interface that shows the media butons with a field next to it where keys and key combinatiosn can be enterd which are then executed when that medi button is pressed.

**Comment by berrberr** [comment]
Yeah it's a cool idea, I have thought of it myself :). This is not possible with the Chrome commands API though unfortunately. You are only allowed to register hotkeys via the extension option page, not programmatically (so we can't do it on the custom option page for example).
