### ISSUE TITLE
Stopped working on pluralsight. Chrome build - Version 79.0.3945.88

### ISSUE THREAD

**Issue by syeuddd** [berrberr/streamkeys#551]
I've used this extension on pluralsight before and it worked fine, not sure what happened but it stopped working, works fine on other sites such as youtube.

**Comment by GarethBlain** [comment]
I created a pull request to fix this a few months ago and it looks like it's just been accepted and merged so I guess it will be in the next release. 🤷‍♂️

https://github.com/berrberr/streamkeys/pull/532
