### ISSUE TITLE
New native media controller broke Streamkeys?

### ISSUE THREAD

**Issue by thw0rted** [berrberr/streamkeys#555]
The last time I updated Chrome -- within the past few days -- I was shown a tooltip highlighting the new "Global Media Controls" feature, a button in the toolbar that I can click to show a dropdown with controls for each tab that includes an audio or video element.  It's a lot like Streamkeys!  The problem is, now Streamkeys doesn't show any media even when I have several Youtube tabs open and one of them is playing.  Even worse, the play/pause button on my keyboard now toggles play/pause on *all media tabs* at once.

Does anybody with the latest (stable) Chrome have their Streamkeys working?  If not, is the project basically dead now?

**Comment by thw0rted** [comment]
As a data point for anybody who comes across this, try turning off all your media-related extensions and see how you like the current native behavior.  The newly released "global media controls" feature is basically a nice, polished native implementation of StreamKeys, so this extension probably isn't really needed anymore.  Make sure you also disable the Google Play Music extension if you have it, because it breaks global play/pause key handling.

**Comment by dmitryshunkov** [comment]
Basically, this new feature covers some of Streamkey functionality, but not all (for example, system notifications, or some actions: like, dislike, song info).

You can disable both new Chrome features to return to the old behaviour:
chrome://flags/#hardware-media-key-handling
chrome://flags/#global-media-controls

> the play/pause button on my keyboard now toggles play/pause on all media tabs at once
It worked in such manner before this Chrome update. You can disable handling of any music tab through the Streamkeys popup window.
