### ISSUE TITLE
Streamkeys doesn't work on MS Edge.

### ISSUE THREAD

**Issue by Sinmok** [berrberr/streamkeys#561]
I've managed to install the extension on the latest (Chromium) edge browser through the Chrome store and I've activated the music sites in settings. I'm on Windows 10 64bit.

Unfortunately,  SK still shows the site as disabled.

![image](https://user-images.githubusercontent.com/4395573/74016636-ab829e00-498a-11ea-951a-bc9f6e00a463.png)

![image](https://user-images.githubusercontent.com/4395573/74016661-b63d3300-498a-11ea-988f-60332eb9e2a2.png)

I've tried restarting my machine and the browser several times with no luck.

Any suggestions?

**Comment by berrberr** [comment]
If the background of the site is red then it's actually disabled. All sites start enabled by default. The UI of that page is really bad so it's confusing 😆
