### ISSUE TITLE
Mixcloud redesign broke Streamkeys integration

### ISSUE THREAD

**Issue by rg1** [berrberr/streamkeys#567]
Mixcloud recently updated their design and it looks like they obfuscated their CSS in the process. As a result, Streamkeys Play/Pause is broken (can't find the element to click). Seeking still seems to work.

**Comment by scporse** [comment]
Hoping for a solution to this as well :)

**Comment by MrJH** [comment]
Hey guys, 
i've fixed the issue - but the selector is now very ugly and will perhaps break again by little changes on mixcloud page.
But perhaps you can give him a try - it's working on my machine ;)

Cheers

**Comment by MrJH** [comment]
Hey Guys,
@nemchik gave me some hints for a better implementation. Just pushed this today.
Cheers

**Comment by rg1** [comment]
It looks to me the fix never made it into the release version published in the chrome app store. Can you look into this, please?

**Comment by nemchik** [comment]
I don't have control over publishing versions to the chrome web store. I've opened an issue that includes this idea as a possibility https://github.com/berrberr/streamkeys/issues/617

Until then you'll have to build locally to get the latest changes, or wait for a release.

**Comment by berrberr** [comment]
@rg1 @MrJH I will publish a release today for this 👍

**Comment by felixpenrose** [comment]
What version of the app does this fix target? It still appears to be broken for me, currently running version 1.8.1
Forward and back do work though

**Comment by felixpenrose** [comment]
Now on 1.8.2 I can confirm it's working again. Thanks 👍

**Comment by berrberr** [comment]
@felixpenrose great, thanks for confirming! Took a while from Google to get update out.
