### ISSUE TITLE
Add support for mutual exclusion

### ISSUE THREAD

**Issue by rzabcik** [berrberr/streamkeys#58]
An extension I used to use had the feature that when one media source was playing and another one started, the new one would pause the old one. I would really like this feature, and I may even do a PR for it.

**Comment by berrberr** [comment]
So the idea is if a new media player is opened and starts playing, all other players that are currently playing will stop? Does this happen as soon as the media player tab is opened, or only when the new media player starts playing?

The default behavior of the extension right now is that it naively sends out a play/pause request, so every player that is playing will be paused, and vice-versa. Each player tab is not aware of the other tab's states.

I am currently in the process of merging some very big changes that I have been working on into master. Amongst other things, one change is the addition of a "stop" function to all sites. Whatever the functionality of this feature is, this new function should be useful (for example, you could send a "stop" request to all active tabs). I'll have the changes merged into master by the end of today if you want to take a look then :).

**Comment by berrberr** [comment]
The changes are up in master now if you want to have a look.

**Comment by nemchik** [comment]
https://github.com/msfeldstein/chrome-media-keys/blob/master/src/background/background.coffee This seems to be what you're looking for (though probably not in coffeeScript)

**Comment by nemchik** [comment]
Another idea would be when a new tab is found playing, pause/stop other tabs and disable the extension on the paused/stopped tabs (your extension has a disable per tab feature that could be leveraged). you'd need to keep a stack of which tabs were most recently playing and then re-enable tabs as the newest ones are closed or no longer contain a player.
