### ISSUE TITLE
Play Previous Track hotkey not working

### ISSUE THREAD

**Issue by blindawson** [berrberr/streamkeys#581]
As of today I'm having an issue with the play previous track hotkey. I tried swapping the key bindings (see below) and the issue seems to be specifically with the Play Previous Track action. I believe this feature worked fine yesterday. Since it doesn't look like streamkeys was updated in the last 24 hours, I'm guessing this is an issue on Pocketcasts' side?

Browser: Chrome Version 80.0.3987.163 (Official Build) (64-bit)
Site: Pocketcasts

Test 1:
- Bindings
  - Play/Pause: Ctrl+G
  - Play Previous Track: Ctrl+Shift+G  
- Result
  - Play/Pause: works fine
  - Play Previous Track: doesn't work

Test 2:
- Bindings:
  - Play/Pause: Ctrl+Shift+G
  - Play Previous Track: Ctrl+G    
- Result: 
  - Play/Pause: works fine
  - Play Previous Track: doesn't work

**Comment by taschmidt** [comment]
Noticed the same thing. Appears to be an easy enough fix. Submitted PR #592
