### ISSUE TITLE
Aliases are not saved

### ISSUE THREAD

**Issue by Tito1337** [berrberr/streamkeys#591]
I'm trying to add an alias for Emby, but it doesn't seem to work.

Adding the alias seems to work OK, but when I go back to the options the aliases are forgotten.

Also, what does the "hostname only" hint mean? Why should'nt it include the www. or .com? The website for which I'm trying to add the alias is on a subdomain, ie. sub.example.com

**Comment by JRichmond27** [comment]
I'm having the same issue. My alias for Plex is gone every time I go back to the StreamKeys options.

**Comment by lozanro** [comment]
Same issue on 
Vivaldi 3.0.1874.38 (Stable channel) (64-bit) / 
User-Agent : Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.142 Safari/537.36
Windows 10 1809

**Comment by ars3nic** [comment]
Same issue here, for a Subsonic server.

Streamkeys 1.8.1
Chrome 83.0.4103.116
Windows 10 LTSC 1809

**Comment by GabrielCalin** [comment]
Yeap, still doesn't work.
