### ISSUE TITLE
Youtube play/pause broken

### ISSUE THREAD

**Issue by t3chguy** [berrberr/streamkeys#608]
As of the last couple of days play/pause has stopped working, instead of working as expected it only pauses the video for a split second and instantly resumes it.
Stop media key also has the same behaviour.

Media Forward still works as expected.
Resuming a paused video works as expected.

The same behaviour is observed when trying to control through the StreamKeys UI.

> StreamKeys: 1.8.1
> Chrome: Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by t3chguy** [comment]
I am still experiencing this issue.

**Comment by jhollowe** [comment]
Do you have anything else controlling the media? Chrome now has a built-in media control system. Make sure to disable this and report back if the issue persists.

**Comment by t3chguy** [comment]
Will try, I tried disabling StreamKeys and media keys didn't do anything so didn't assume blame on Chrome

**Comment by t3chguy** [comment]
I disabled `chrome://flags/#hardware-media-key-handling` and still experience this issue

**Comment by t3chguy** [comment]
I noticed that if I focus/have the Youtube tab active then it does work as expected
