### ISSUE TITLE
Forward event to system if no applicable player in browser

### ISSUE THREAD

**Issue by jlous** [berrberr/streamkeys#63]
I pefer the dedicated desktop app for Spotify, but Soundcloud doesn't have one for Windows, so I have to use that in the browser.
I'd like to use the same keys for both.

If I disable sreamkeys, I can control spotify from the keyboard.
If I enable streamkeys, it seems to gobble up the events even if I have no players open in chrome, so Spotify doensn't respond.

Oddly, it seemed to work the way I want when I first installed the plugin, but not after rebooting.

**Comment by berrberr** [comment]
Unfortunately this is a bug/issue with Chrome and doesn't look like it will be fixed anytime soon :(.

See this issue for more info and possible solutions: #42
