### ISSUE TITLE
Add support for bandcamp subpages

### ISSUE THREAD

**Issue by berrberr** [berrberr/streamkeys#66]
Some bandcamp player pages are hosted on other domains (ie: http://shop.silentseason.com/album/aeterna). Since we inject contentscript into pages based on domain the bandcamp controller is not injected into these pages.

**Comment by inverse** [comment]
I'll be interesting to see how you handle this. There is an active issue on the web-scrobbler extension about this.

https://github.com/david-sabata/web-scrobbler/issues/334

**Comment by motla** [comment]
Still interested for this enhancement! 😉 
Another example that doesn't work : https://music.tomday.me/album/fables
