### ISSUE TITLE
debounce between actions

### ISSUE THREAD

**Issue by wtfil** [berrberr/streamkeys#67]
Hi!
I like your work, but have few issues:)

I am using Google music as music service and it allow to use the "google music app" (chrome app). Correct me if I wrong, but there is two music tabs when "music app" lunched, and when I trying to pause the song with hotkey I can hear small pause(interruption), but music continues.
Sound like I quickly pressed "pause" button for two times.

Sometimes I had reproduce this but on vk.com but I have not strict flow to describe it better. It could be related to what I described above.

Anyway, I think, that simple debounce between action will be enough to prevent this.

Tnx!

**Comment by berrberr** [comment]
Hey, thanks for the info! I (think) the problem is that the Google music app defaults it's hotkeys to use the media keys as well. So if Streamkeys + Google music app both use the media keys then pressing play/pause will actually send two play/pause actions which would explain the music pausing shortly then starting again.

The fix in this case would either be changing the Streamkeys hotkey or the Google music app hotkey.

I could be way off base here though...let me know if I misunderstood your question.

**Comment by wtfil** [comment]
Google music App does not use any of system keys (at least on Mac) :musical_note:

**Comment by berrberr** [comment]
Hmm, I can't reproduce this. Let me know if one of these steps is incorrect:

1. Install Google Play Music app (https://chrome.google.com/webstore/detail/google-play-music/icppfcnhkcmnfdhfhphakoifcfokfdhg?hl=en)

2. Goto chrome://apps and click on the Play Music app

3. Start playing something and try to use Streamkeys play/pause...and it works fine.

Let me know the steps that you take to produce this :)

**Comment by wtfil** [comment]
@berrberr Yeah, I do the same:)

Seems like I have the problem with OS environment. Going to investigate it deeply)
I am noobie in Chrome Extensions, so it could take some time.  I will let you know what I found, may be it will be useful. So far, seems like this issue may be closed :)

**Comment by Atema** [comment]
It's not the Google Play Music app that causes the problem, but the Google Play Music extension (https://chrome.google.com/webstore/detail/google-play-music/fahmaaghhglfmonjliepjlchgpgfmobi). It uses the Chrome built-in hotkeys, and StreamKeys works again when disabling the keys for the Play Music extension.

**Comment by berrberr** [comment]
Yes, that is what I think the issue probably is as well. I'll mention it on the site and extension page since this seems to be a pretty common problem (I get a lot of messages about it).

I'll leave this open for now incase @wtfil finds something that I missed...
