### ISSUE TITLE
Hotkeys doesn't work when chrome is not on focus

### ISSUE THREAD

**Issue by danilolutti** [berrberr/streamkeys#682]
I can control udemy playback only if chrome app is selected/focused. 
If I click on desktop, shortcuts play/pause doesn't work anymore

**Comment by arpitkaushal** [comment]
> I can control udemy playback only if chrome app is selected/focused.
> If I click on desktop, shortcuts play/pause doesn't work anymore

You could give the following steps a try. Might fix your issue :)
 
1. Go to the General Settings on the extension page, and click on configure hotkeys.  
`or` Go to chrome://extensions/shortcuts on your browser. 
![temp1](https://user-images.githubusercontent.com/44678651/98432139-5e7e5480-20e1-11eb-85d9-44bd884949dd.JPG)

2. You'll reach the following page. 
![image](https://user-images.githubusercontent.com/44678651/98432155-7ce45000-20e1-11eb-94d8-833996c5e3c7.png)
Once here, just select, `Global` for the options that you want to work outside of Chrome.

**Comment by danilolutti** [comment]
thank you, it worked.
