### ISSUE TITLE
Spotify not responding

### ISSUE THREAD

**Issue by Architectuur** [berrberr/streamkeys#699]
Spotify is not responding to certain hotkeys. I use alt+V to play pause and alt+Z for play previous and those are not working. But I use alt+X for play next and that still works. 

I looked through chromes hotkeys and these are not in use by Chrome. Did something else change? I've been using streamkeys with these hotkeys for years.

**Comment by evilarceus** [comment]
Spotify just updated to where the next button no longer works :(

To fix it, it might be as easy as checking if the button has the `title` attribute set to `Play`/`Pause`/`Previous`/`Next`, but I'm pretty sure that attribute changes depending on the user's language.

**Comment by alexesprit** [comment]
Should be fixed in #698.

**Comment by pikess** [comment]
> Should be fixed in #698.

Thank you!!! Any ETA on that release?

**Comment by Architectuur** [comment]
So is this supposed to be fixed? It is still not working for me..

**Comment by alexesprit** [comment]
It's fixed, but not released yet.

**Comment by berrberr** [comment]
The new version (v1.8.3) is submitted to the Chrome store for review now. Hopefully it will be approved soon ... I think this process has gotten a bit slower unfortunately due to permissions required for this extension to work.

Apologies all for the delay, happy new year 🎉
