### ISSUE TITLE
Deezer doesn't work

### ISSUE THREAD

**Issue by PavleKreator** [berrberr/streamkeys#70]
Maybe they changed their website, because it is in the supported list, but media controls do not work.

**Comment by berrberr** [comment]
I can't reproduce this, it is working for me. http://www.deezer.com/ is the site I am testing. Let me know what steps you took to produce this. Thanks.

**Comment by PavleKreator** [comment]
You are right, it is working, I'm sorry I disturbed you.

**Comment by berrberr** [comment]
No problem :)
