### ISSUE TITLE
Grunt error 'controller' is assigned a value but never used  no-unused-vars

### ISSUE THREAD

**Issue by VarunAgw** [berrberr/streamkeys#707]
I got this while running `grunt dev`.

https://github.com/berrberr/streamkeys/blob/master/code/js/controllers/SpotifyController.js

Removing `var controller = ` in this file seemed to fix it.

P.S. Please release the latest changes to Chrome store, so we don't have to build it ourself 🙃

**Comment by berrberr** [comment]
Thanks for the report! Fixed
