### ISSUE TITLE
Grooveshark is not working anymore

### ISSUE THREAD

**Issue by Daazku** [berrberr/streamkeys#71]
They do not use www. anymore.

Update [code/js/modules/Sitelist.js]
www.grooveshark.com -> grooveshark.com

**Comment by berrberr** [comment]
Can't reproduce this - the new grooveshark works for me. Also the "www." part of the URL doesn't matter - the regex will check for both the hostname and "www." + the hostname.

Let me know if there are some steps I can take reproduce this, and if the extension is working for you on other sites. Thanks.

**Comment by Daazku** [comment]
I'm on openSUSE with chrome 41.0.2272.76 (64-bit).
I got the extension from the webstore.

Your extension was working with youtube but not with grooveshark.
I had to edit the url from www.grooveshark.com to grooveshark.com to make it work.

**Comment by Daazku** [comment]
Well, I have no clue why it didn't work at first but I uninstalled and reinstaller the plugin and it worked first shot. Maybe it was because i needed to reload the tab after the plugin installation.

All is working. Thanks for the quick reply and sorry for your time.
