### ISSUE TITLE
PocketCasts play/pause stopped working

### ISSUE THREAD

**Issue by Wizek** [berrberr/streamkeys#716]
https://play.pocketcasts.com/podcasts

**Comment by berrberr** [comment]
@Wizek Thanks for the report. I don't have access to that site so I can't fix it. You probably need to update the selector if you would like to make a pull request. The file to change is this: https://github.com/berrberr/streamkeys/blob/master/code/js/controllers/PocketcastsController.js#L7

**Comment by Wizek** [comment]
Thanks, the does indeed seems to be simple to update there.
However, they may have changed the class on the button back because it seems to work again.

I'm closing this for now and if the issue pops up again I'll know where to look.
