### ISSUE TITLE
Netflix play/pause broken

### ISSUE THREAD

**Issue by jhollowe** [berrberr/streamkeys#751]
It appears that Netflix has changed their UI. The play/pause button now has a random class (shown below).

Error from console: `STREAMKEYS-ERROR: Element not found for click. .button-nfplayerPlay`

Element:
```html
<button aria-label="Play" class=" ltr-1enhvti" data-uia="control-play-pause-play">
  <div class="medium ltr-dguo2f" role="presentation">
    <svg viewBox="0 0 24 24"><g id="play"><polygon fill="currentColor" points="6 4 21 12 6 20"></polygon></g></svg> 
 </div>
</button>
```

**Comment by fdendorfer** [comment]
Can we reopen this. It's still an issue
