### ISSUE TITLE
Spotify Web Player Issues

### ISSUE THREAD

**Issue by TylerAnderson22** [berrberr/streamkeys#771]
SteamKeys has stopped working with Spotify Web Player.

**Comment by erik434** [comment]
I can confirm that play/pause seems to have stopped working in the Spotify web player, and Streamkeys doesn't seem to be able to read the current play/pause state either: if I hit play/pause in Spotify, Streamkeys always shows the Spotify tab is paused, even if that's not correct. The "back" command still seems to work fine however.

This is in Chrome 90.0.4430.212 with Streamkeys 1.8.3.

**Comment by Architectuur** [comment]
How do we get this implemented? Its been a while...

**Comment by VarunAgw** [comment]
@berrberr Bump. Any update?
