### ISSUE TITLE
Feature Request: Youtube fast foward and backwards

### ISSUE THREAD

**Issue by taoliu12** [berrberr/streamkeys#816]
This is the "l" and "j" local hotkeys normal on Youtube.

I would like to be able to assign global hotkeys to fast forward or rewind on videos.

Thanks

**Comment by nendonerd** [comment]
wish to assign global hotkeys to invoke custom keyboard event on a page, such as assigning << and >> on mac keyboard to left/right arrow key on youtube, to rewind/fast-forward videos

**Comment by nendonerd** [comment]
just figure out a way to programmatically trigger the rewind/fast-forward for youtube in console
`
const event = new KeyboardEvent('keydown', {
    key: 'ArrowRight',  // 'ArrowLeft' for rewind
    bubbles: true,
    cancelable: true,
    composed: true,
    keyCode: 39,  // 37 for rewind
    which: 39,  // 37 for rewind
  });
  const body = document.querySelector('body');
  body.dispatchEvent(event)
`
