### ISSUE TITLE
USB keyboard media keys not working

### ISSUE THREAD

**Issue by jheckey** [berrberr/streamkeys#83]
Hi. Great extension, glad to have it installed. I'm currently using it on my laptop, and it works fine with the laptop's built-in media keys.

Unfortunately, my USB keyboard doesn't get the media keys through. My Bluetooth headset also can send media keys which don't work either. These keys **do** work with Windows Media Player. Not sure if this is an extension issue or a Chrome issue. Normal hotkeys (e.g., Ctrl+Shift+2) do work from the USB keyboard.

Laptop: Dell Latitiude E7440
Keyboard: MS Natural Ergonomic 4000
Headset: Velodyne vBold

-Thanks!

**Comment by berrberr** [comment]
Hey,

I think that this is a bug with Chrome for some Microsoft drivers and keyboards. Other users have reported this problem as well, and the solution seems to be uninstalling "Microsoft Keyboard and Mouse Center" software and/or drivers. See this thread for reference and other possible fixes: https://code.google.com/p/chromium/issues/detail?id=405366

Let me know if it works! I'll put this in the FAQ on the site too...

**Comment by jheckey** [comment]
Hi Alex,

Thanks for the quick update! I'll try that out and see if it helps.

-Jeff

**Comment by blalond** [comment]
I confirm that uninstall of "microsoft mouse and keyboard center" worked on windows 10.
