### ISSUE TITLE
Media keys do not work for soundcloud anymore

### ISSUE THREAD

**Issue by MarcKamradt** [berrberr/streamkeys#84]
It seems the newest version of soundcloud cannot be controlled anymore.

I can still control sites like bandcamp and youtube.

Marc

**Comment by berrberr** [comment]
It works for me. Can you post a link to the soundcloud page that isn't working?

**Comment by inverse** [comment]
It's working here.

**Comment by MarcKamradt** [comment]
No idea why but I just tested it and now it works fine. However I had this issue for a few days straight.

I will close the issue for now...

Thanks for the cool extension and keep up the good work.

Marc
