### ISSUE TITLE
Youtube Play/Pause not working at all

### ISSUE THREAD

**Issue by Elmazz37** [berrberr/streamkeys#844]
Neither the hotkeys, nor the StreamKeys popup window has a working pause/play functionality. It just does nothing. I don't see anyone talking about this, so I assume this is on something on my end? Anyone experienced this issue before? Using Brave browser.

**Comment by KyrumX** [comment]
Having the same issue. Refreshing until it works again fixes it.

**Comment by Haapavuo** [comment]
Same issue here for a several weeks already. Must be a new issue caused by a YouTube update. Any ideas?

**Comment by Elmazz37** [comment]
For anyone finding this. Uninstall other extentions you have and see if it helps. I uninstalled "Youtube Nonstop" and installed "You(Tube) don't stop!" and that fixed this issue.
