### ISSUE TITLE
Deezer - play previous or next track not working

### ISSUE THREAD

**Issue by abg88** [berrberr/streamkeys#913]
**It's fixed as follows. Thanks to max-collomb.**

> Reading comments on issue #845, I'm not sure this PR will be treated. Thus, I post an alternative while waiting for a patched version
> 
> For Edge on Windows (adapt path for another browser) :
> 
> * list extensions in the browser (edge://extensions/)
> * activate developer mode
> * retrieve streamkey extension ID
> * Edit file `C:\Users\%username%\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\{{id}}\1.8.4_0\js\controllers\DeezerController.js` and remove `div > ` on lines 9, 11 and 15
> * close and reopen the browser

----

Those two hotkeys stopped working a while ago in Deezer. "Toggle Play/Pause" still works just fine in Deezer though.
"Play previous or next track" hotkeys work just fine in YouTube Music and Spotify.

EDIT: bellow there's a screenshot of how Streamkeys appears in Chrome. All buttons except Play/Pause are greyed out for Deezer, and all are available for YouTube Music. 

![image](https://user-images.githubusercontent.com/8398363/174873888-503ab0c0-987f-4e69-8d9c-d8f0ba8cb587.png)

**Comment by max-collomb** [comment]
Reading comments on issue #845, I'm not sure this PR will be treated.
Thus, I post an alternative while waiting for a patched version

For Edge on Windows (adapt path for another browser) :
- list extensions in the browser (edge://extensions/)
- activate developer mode
- retrieve streamkey extension ID
- Edit file `C:\Users\%username%\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\{{id}}\1.8.4_0\js\controllers\DeezerController.js` and remove `div > ` on lines 9, 11 and 15
- close and reopen the browser

**Comment by abg88** [comment]
> Those two hotkeys stopped working a while ago in Deezer. "Toggle Play/Pause" still works just fine in Deezer though. "Play previous or next track" hotkeys work just fine in YouTube Music and Spotify.
> 
> EDIT: bellow there's a screenshot of how Streamkeys appears in Chrome. All buttons except Play/Pause are greyed out for Deezer, and all are available for YouTube Music.
> 
> <img alt="image" width="288" height="284" src="https://user-images.githubusercontent.com/8398363/174873888-503ab0c0-987f-4e69-8d9c-d8f0ba8cb587.png">

Thank you so much! It's now working perfectly in Chrome.

**Comment by abg88** [comment]
It's fixed as follows. Thanks to max-collomb.

Reading comments on issue https://github.com/berrberr/streamkeys/issues/845, I'm not sure this PR will be treated. Thus, I post an alternative while waiting for a patched version

For Edge on Windows (adapt path for another browser) :

list extensions in the browser (edge://extensions/)
activate developer mode
retrieve streamkey extension ID
Edit file C:\Users\%username%\AppData\Local\Microsoft\Edge\User Data\Default\Extensions\{{id}}\1.8.4_0\js\controllers\DeezerController.js and remove div > on lines 9, 11 and 15
close and reopen the browser

**Comment by randomComitter** [comment]
There is already a PR for this fix, would be good if someone could merge it and release a new version:
https://github.com/berrberr/streamkeys/pull/927

Meanwhile, manually applying the same change in the DeezerController.js (as written above) does the trick.
