### ISSUE TITLE
YouTube HTML5 player broken

### ISSUE THREAD

**Issue by inverse** [berrberr/streamkeys#92]
Could be related to the new roll out of the YouTube player (HTML5).

Example URL: https://www.youtube.com/watch?v=h5tx4L1MqZQ
Chrome: Version 43.0.2357.37 beta-m (64-bit) (Windows)

**Comment by Edmundo096** [comment]
Same thing here. HTML5. Example of other video https://www.youtube.com/watch?v=aDaDU8yjgF8
Chrome 42.0.2311.135 m (64-bit)

**Comment by berrberr** [comment]
Hmm, I can't replicate this. I tried both those videos on Chrome 43.0.2357.45 (Official Build) beta (64-bit).

It definitely is the HTML5 player (right click on the video, I see: About HTML5 player) and the extension works.

@inverse  @Edmundo096: Any other steps that you took to reproduce?

**Comment by Edmundo096** [comment]
Hmm, I will try after restarting Windows (and thus Chrome).
But for now, I opened the Dev tools with another YT video, and the same, Play/Pause KB key has no action, but the console displays this:
```
STREAMKEYS-ERROR: Element not found for click. .ytp-button-pause   
b.exports @ YoutubeController.js:1
c.click @ YoutubeController.js:1
c.playPause @ YoutubeController.js:1
c.doRequest @ YoutubeController.js:1
target.(anonymous function) @ extensions::SafeBuiltins:19
.......... (and the stack continues with more @ extensions:..)
```

**Comment by Edmundo096** [comment]
Restarting didn't changed anything.
For your info, here is how the button tag on YT is when a video is playing:
```html
<button class="ytp-play-button ytp-button ytp-play-button-pause" aria-live="assertive" tabindex="30" aria-label="Pause"></button>
```
And this is when paused:
```html
<button class="ytp-play-button ytp-button ytp-play-button-play" aria-live="assertive" tabindex="30" aria-label="Play"></button>
```
I think its maybe the class that is different, maybe a different HTML5 player?
Seems that its `ytp-play-button-{new state}`
Hope it helps @berrberr

**Comment by berrberr** [comment]
Awesome exactly what I was looking for, thanks for the help @Edmundo096.

Yup, it's actually a different player with different CSS selectors ... I was able to enable the new player by visiting: www.youtube.com/testtube and now can replicate the problem.

The problem now is that a single site has two different players for the same domain (and controller). Surprisingly this hasn't come up yet!

The solution should be pretty easy however. I'll override the `click` method in the youtube controller to check for a selector to see which version of the player is on the page and send clicks to the correct selector accordingly.

**Comment by Edmundo096** [comment]
Glad I could help @berrberr 
And yes, didn't noticed that, indeed, I was using the new player from testtube.

Interesting to know what would be the solution of the issue. Thanks!

**Comment by berrberr** [comment]
Fixed! Will push changes shortly. Thanks for the help @Edmundo096

**Comment by Edmundo096** [comment]
@berrberr Just received the update today in the morning, working great. Thanks!
